package com.cefettrainer.app;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.os.*;
import android.view.*;
import android.widget.*;

import java.util.*;

/** Simulado v0.10: 30 questões contextualizadas, 4h, textos-base compartilhados e correção explicada. */
public class ExamV10Activity extends Activity {
    private final int NAVY=Color.rgb(13,43,74), BLUE=Color.rgb(28,91,150), GREEN=Color.rgb(34,131,94), RED=Color.rgb(183,61,61), AMBER=Color.rgb(180,118,20), BG=Color.rgb(246,248,251), TEXT=Color.rgb(27,38,49), MUTED=Color.rgb(82,96,109);
    private final Random r=new Random();
    private final ArrayList<Q> questions=new ArrayList<>();
    private final ArrayList<RadioGroup> groups=new ArrayList<>();
    private SharedPreferences prefs;
    private long endAt;
    private TextView clock;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private boolean finished=false;

    @Override public void onCreate(Bundle b){
        super.onCreate(b);getWindow().setStatusBarColor(NAVY);prefs=getSharedPreferences("cefet_v10_learning",MODE_PRIVATE);
        generate();endAt=System.currentTimeMillis()+4L*60*60*1000;showExam();handler.post(tick);
    }
    private TextView tv(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(TEXT);v.setPadding(10,8,10,8);v.setLineSpacing(2,1.08f);if(bold)v.setTypeface(null,1);return v;}
    private TextView muted(String s,int sp){TextView v=tv(s,sp,false);v.setTextColor(MUTED);return v;}
    private Button button(String s,int color,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(Color.WHITE);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(color));b.setMinHeight(54);b.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,6,0,6);b.setLayoutParams(p);return b;}
    private LinearLayout root(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(18,18,18,32);x.setBackgroundColor(BG);return x;}
    private ScrollView page(LinearLayout x){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(x);return s;}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(14,12,14,12);c.setBackgroundColor(Color.WHITE);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,7,0,7);c.setLayoutParams(p);return c;}

    private void showExam(){
        LinearLayout x=root();x.addView(button("← Sair do simulado",NAVY,v->confirmExit()));
        x.addView(tv("Simulado CEFET — 30 questões",27,true));
        x.addView(muted("10 Português • 10 Matemática • 5 Ciências da Natureza • 5 Ciências Humanas • tempo de treino: 4 horas",14));
        clock=tv("04:00:00",23,true);clock.setGravity(Gravity.CENTER);x.addView(clock);
        String lastContext=null;int n=1;
        for(Q q:questions){
            if(q.context!=null&&!q.context.isEmpty()&&!q.context.equals(lastContext)){
                LinearLayout tc=card();tc.addView(tv(q.contextTitle==null?"Texto-base":q.contextTitle,18,true));tc.addView(tv(q.context,16,false));x.addView(tc);lastContext=q.context;
            } else if(q.context==null||q.context.isEmpty()) lastContext=null;
            LinearLayout qc=card();qc.addView(tv(n+". ["+q.subject+" • "+q.topic+"]",13,true));qc.addView(tv(q.prompt,17,true));
            RadioGroup g=new RadioGroup(this);g.setOrientation(RadioGroup.VERTICAL);
            for(int i=0;i<4;i++){RadioButton rb=new RadioButton(this);rb.setId(3000+n*10+i);rb.setText((char)('A'+i)+") "+q.options[i]);rb.setTextSize(16);rb.setPadding(6,8,6,8);g.addView(rb);}groups.add(g);qc.addView(g);x.addView(qc);n++;
        }
        x.addView(button("Finalizar e corrigir",GREEN,v->finishExam(false)));
        x.addView(muted("A correção só aparece depois de responder todas as questões. Durante o simulado não há feedback imediato, para ficar mais parecido com a prova.",13));
        setContentView(page(x));
    }

    private void confirmExit(){new AlertDialog.Builder(this).setTitle("Sair do simulado?").setMessage("As respostas deste simulado serão descartadas.").setNegativeButton("Continuar",null).setPositiveButton("Sair",(d,w)->finish()).show();}

    private final Runnable tick=new Runnable(){@Override public void run(){if(finished||clock==null)return;long left=endAt-System.currentTimeMillis();if(left<=0){clock.setText("Tempo encerrado");finishExam(true);return;}long s=left/1000;clock.setText(String.format(Locale.getDefault(),"%02d:%02d:%02d",s/3600,(s%3600)/60,s%60));handler.postDelayed(this,500);}};

    private void finishExam(boolean timeUp){
        if(finished)return;
        int unanswered=0;for(RadioGroup g:groups)if(g.getCheckedRadioButtonId()==-1)unanswered++;
        if(unanswered>0&&!timeUp){Toast.makeText(this,"Ainda faltam "+unanswered+" questão(ões). Responda tudo antes de corrigir.",Toast.LENGTH_LONG).show();return;}
        finished=true;handler.removeCallbacks(tick);
        int hit=0;int[] areaHit=new int[4],areaTotal=new int[4];
        for(int i=0;i<questions.size();i++){
            Q q=questions.get(i);int area=areaIndex(q.subject);areaTotal[area]++;
            int id=groups.get(i).getCheckedRadioButtonId();int chosen=id==-1?-1:id-3000-(i+1)*10;
            if(chosen==q.correct){hit++;areaHit[area]++;}
            recordTopic(q,chosen==q.correct);
        }
        int oldPoints=prefs.getInt("exam_points",0);int ready=prefs.getInt("exam_ready",0);SharedPreferences.Editor e=prefs.edit();e.putInt("exam_points",oldPoints+hit*10).putInt("exam_tests",prefs.getInt("exam_tests",0)+1);if(hit==30){ready=Math.min(100,ready+5);e.putInt("exam_ready",ready).putInt("exam_perfect",prefs.getInt("exam_perfect",0)+1);}e.apply();
        showResult(hit,areaHit,areaTotal,timeUp);
    }

    private int areaIndex(String s){if(s.equals("Português"))return 0;if(s.equals("Matemática"))return 1;if(s.equals("Física")||s.equals("Química")||s.equals("Biologia"))return 2;return 3;}
    private void recordTopic(Q q,boolean ok){String k="examTopic::"+q.subject+"||"+q.topic;int a=prefs.getInt(k+"::a",0)+1,c=prefs.getInt(k+"::c",0)+(ok?1:0);prefs.edit().putInt(k+"::a",a).putInt(k+"::c",c).apply();}

    private void showResult(int hit,int[] ah,int[] at,boolean timeUp){
        LinearLayout x=root();x.addView(button("← Voltar ao treino",NAVY,v->finish()));
        int pct=Math.round(hit*100f/30f);x.addView(tv("Resultado: "+hit+"/30 — "+pct+"%",28,true));if(timeUp)x.addView(tv("O tempo de 4 horas terminou; questões em branco foram consideradas incorretas.",14,true));
        LinearLayout summary=card();summary.addView(tv("Por área",19,true));summary.addView(tv("Português: "+ah[0]+"/"+at[0],16,false));summary.addView(tv("Matemática: "+ah[1]+"/"+at[1],16,false));summary.addView(tv("Ciências da Natureza: "+ah[2]+"/"+at[2],16,false));summary.addView(tv("Ciências Humanas: "+ah[3]+"/"+at[3],16,false));x.addView(summary);
        for(int i=0;i<questions.size();i++){
            Q q=questions.get(i);int id=groups.get(i).getCheckedRadioButtonId();int chosen=id==-1?-1:id-3000-(i+1)*10;boolean ok=chosen==q.correct;
            LinearLayout c=card();TextView h=tv((i+1)+". "+(ok?"✓ Acertou":"✗ Errou")+" — "+q.topic,16,true);h.setTextColor(ok?GREEN:RED);c.addView(h);c.addView(tv(q.prompt,15,false));c.addView(tv("Sua resposta: "+(chosen<0?"em branco":String.valueOf((char)('A'+chosen)))+"   •   correta: "+(char)('A'+q.correct),14,true));
            if(chosen>=0&&!ok)c.addView(tv("Por que sua alternativa não funciona: "+q.wrongWhy(chosen),14,false));c.addView(tv("Por que a correta funciona: "+q.explain,14,false));x.addView(c);
        }
        x.addView(button("Gerar outro simulado",BLUE,v->{generate();groups.clear();finished=false;endAt=System.currentTimeMillis()+4L*60*60*1000;showExam();handler.post(tick);}));
        setContentView(page(x));
    }

    private void generate(){questions.clear();questions.addAll(portugueseSet());for(int i=0;i<10;i++)questions.add(mathQuestion(i));ArrayList<Q> nat=natureSet();Collections.shuffle(nat,r);ArrayList<Q> selectedNat=new ArrayList<>();selectedNat.add(firstOf(nat,"Física"));selectedNat.add(firstOf(nat,"Química"));selectedNat.add(firstOf(nat,"Biologia"));for(Q q:nat)if(selectedNat.size()<5&&!selectedNat.contains(q))selectedNat.add(q);questions.addAll(selectedNat.subList(0,5));ArrayList<Q> hum=humanSet();Collections.shuffle(hum,r);ArrayList<Q> selectedHum=new ArrayList<>();selectedHum.add(firstOf(hum,"História"));selectedHum.add(firstOf(hum,"Geografia"));for(Q q:hum)if(selectedHum.size()<5&&!selectedHum.contains(q))selectedHum.add(q);questions.addAll(selectedHum.subList(0,5));}
    private Q firstOf(ArrayList<Q> a,String subject){for(Q q:a)if(q.subject.equals(subject))return q;throw new IllegalStateException(subject);}

    private ArrayList<Q> portugueseSet(){
        ArrayList<Q>a=new ArrayList<>();
        String ta="A biblioteca da escola decidiu reorganizar o empréstimo de livros depois de perceber uma mudança curiosa. O número de estudantes que entrava no espaço havia diminuído, mas os pedidos de indicação de leitura enviados pelo aplicativo da escola aumentaram. Em vez de concluir que os jovens haviam deixado de ler, a equipe comparou os registros e descobriu que muitos alunos começavam uma pesquisa no celular e, depois, procuravam um livro impresso para aprofundar o assunto. A bibliotecária passou então a publicar pequenas trilhas de leitura, combinando textos digitais curtos com capítulos de livros. A proposta não tratava uma tecnologia como inimiga da outra: buscava aproveitar a rapidez de uma e a possibilidade de concentração oferecida pela outra. Após alguns meses, os empréstimos cresceram e mais estudantes passaram a comentar as leituras em encontros presenciais.";
        a.add(q("Português","Inferência","Texto 1",ta,"A partir do texto, qual conclusão é mais bem sustentada?",new String[]{"A redução inicial de visitas significava abandono definitivo da leitura.","Práticas digitais e impressas podem se complementar no percurso de leitura.","O aplicativo substituiu totalmente os livros impressos.","Os encontros presenciais foram cancelados após a reorganização."},1,"Os dados mostraram estudantes iniciando pesquisas no celular e aprofundando-as em livros; a estratégia posterior combinou os dois meios.",new String[]{"O próprio texto mostra que a equipe evitou essa conclusão e encontrou outro comportamento.","","O texto afirma o contrário: os empréstimos impressos cresceram.","Os encontros presenciais passaram a receber comentários de leitura."}));
        a.add(q("Português","Coesão e conectivos","Texto 1",ta,"No trecho 'Em vez de concluir que os jovens haviam deixado de ler, a equipe comparou os registros...', a expressão inicial estabelece principalmente uma relação de:",new String[]{"substituição de uma interpretação por outra ação de investigação","adição de duas causas equivalentes","explicação de uma consequência inevitável","marcação de tempo futuro"},0,"'Em vez de' apresenta aquilo que não foi feito e introduz a ação escolhida no lugar: comparar os registros.",new String[]{"","Não há simples soma de ideias equivalentes.","A segunda ação não é apresentada como consequência inevitável.","A expressão não marca futuro."}));
        a.add(q("Português","Referência pronominal","Texto 1",ta,"Em 'aproveitar a rapidez de uma e a possibilidade de concentração oferecida pela outra', os termos 'uma' e 'outra' retomam:",new String[]{"biblioteca e escola","pesquisa e capítulo","tecnologia digital e leitura impressa","bibliotecária e equipe"},2,"O período contrasta os dois suportes mencionados imediatamente antes: digital e impresso.",new String[]{"Esses espaços não são o par contrastado nesse trecho.","São elementos das trilhas, mas 'uma/outra' retomam as tecnologias/suportes.","","Pessoas não são o referente da oposição."}));
        a.add(q("Português","Tese e ideia central","Texto 1",ta,"Qual formulação resume melhor a ideia central do texto?",new String[]{"A escola deve proibir celulares para recuperar o hábito de leitura.","A observação de dados permitiu criar uma estratégia que articulou diferentes formas de leitura.","Livros impressos só funcionam quando não existe acesso digital.","O aumento de empréstimos ocorreu antes de qualquer mudança da biblioteca."},1,"O texto mostra uma decisão baseada nos registros e uma estratégia de combinação entre leitura digital e impressa.",new String[]{"A proposta explicitamente não tratou uma tecnologia como inimiga da outra.","","O texto defende complementaridade, não exclusão.","O aumento veio após a reorganização."}));

        String dialog="Diálogo:\n— Você terminou o relatório? — perguntou Lia.\n— Terminei a pesquisa, mas ainda preciso organizar os dados — respondeu Caio.\n— Então não diga que o relatório está pronto. A pesquisa é uma parte dele.";
        a.add(q("Português","Sentido contextual","Situação 2",dialog,"No diálogo, a fala final de Lia corrige Caio porque diferencia:",new String[]{"a etapa de pesquisar do produto final organizado","uma opinião de um fato científico","a linguagem formal da informal","o singular do plural"},0,"Lia mostra que concluir a pesquisa não equivale a finalizar o relatório; pesquisa é apenas uma etapa.",new String[]{"","O foco não é classificar opinião e fato.","A correção é conceitual, não de registro linguístico.","Número gramatical não é o problema."}));
        a.add(q("Português","Discurso direto e pontuação","Situação 2",dialog,"Os travessões do diálogo cumprem principalmente a função de:",new String[]{"separar sílabas de palavras longas","marcar as falas das personagens e organizar a alternância de vozes","indicar que todas as frases são perguntas","substituir obrigatoriamente todas as vírgulas"},1,"No texto dialogado, os travessões introduzem as falas e ajudam a distinguir quem está falando.",new String[]{"Não têm função de separação silábica nesse caso.","","Há falas afirmativas e interrogativas.","Travessão e vírgula têm funções diferentes."}));

        String tb="Em muitos bairros, uma praça é julgada apenas pela quantidade de equipamentos que possui. Bancos novos, quadras e iluminação são importantes, mas não garantem, sozinhos, que o espaço seja usado. Quando moradores não participam das decisões, uma reforma pode criar estruturas pouco adequadas às rotinas locais. Em um bairro fictício chamado Horizonte, por exemplo, a prefeitura instalou mesas de jogos em uma área sem sombra. Durante o dia, quase ninguém permanecia ali. Depois de reuniões com moradores, parte das mesas foi deslocada para perto das árvores e uma área livre foi mantida para feiras. O movimento aumentou. O episódio sugere que planejar um espaço público envolve observar usos reais, ouvir diferentes grupos e adaptar o projeto. Participação não elimina conflitos: jovens, comerciantes, idosos e crianças podem desejar coisas diferentes. Ela permite, contudo, que essas diferenças apareçam antes que uma decisão se transforme em obra difícil de modificar.";
        a.add(q("Português","Argumento e evidência","Texto 3",tb,"O caso do bairro Horizonte funciona no texto principalmente como:",new String[]{"evidência concreta que exemplifica a importância de observar os usos do espaço","prova de que toda praça deve ter mesas de jogos","argumento para eliminar áreas de feira","informação sem relação com a ideia defendida"},0,"O exemplo mostra uma reforma inicialmente pouco adequada e a melhora após ouvir moradores e adaptar o espaço.",new String[]{"","O texto não transforma uma solução local em regra universal.","A área de feira foi preservada, não eliminada.","O episódio sustenta diretamente a ideia central."}));
        a.add(q("Português","Conectivo adversativo","Texto 3",tb,"No final do texto, o conectivo 'contudo' introduz uma ideia que:",new String[]{"repete sem alteração a afirmação anterior","contrasta com a limitação apresentada e mostra uma utilidade da participação","explica a causa de todas as reformas","indica uma sequência cronológica obrigatória"},1,"Antes, o texto admite que participação não elimina conflitos; 'contudo' contrapõe a isso o benefício de tornar as diferenças visíveis antes da obra.",new String[]{"Há contraste, não repetição.","","Não apresenta causa de todas as reformas.","A relação é argumentativa, não simplesmente temporal."}));
        a.add(q("Português","Fato e avaliação","Texto 3",tb,"Qual alternativa apresenta uma informação do exemplo narrado, e não uma generalização ou avaliação?",new String[]{"Toda reforma sem consulta pública fracassa.","A prefeitura instalou mesas em uma área sem sombra e depois deslocou parte delas.","Ouvir moradores é sempre a única solução possível.","Praças com quadras são necessariamente melhores."},1,"Essa alternativa recupera acontecimentos explicitamente narrados no caso de Horizonte.",new String[]{"O texto não afirma que toda reforma fracassa.","","A participação é defendida, mas não como única solução universal.","O texto rejeita avaliações tão automáticas."}));
        a.add(q("Português","Inferência","Texto 3",tb,"Considerando o texto inteiro, por que é importante que divergências apareçam antes da execução da obra?",new String[]{"Porque depois de construída, uma solução inadequada pode ser mais difícil de alterar.","Porque conflitos desaparecem quando são antecipados.","Porque apenas comerciantes podem decidir sobre espaços públicos.","Porque equipamentos novos são sempre desnecessários."},0,"A última frase afirma que tornar as diferenças visíveis antes evita que a decisão se transforme em uma obra difícil de modificar.",new String[]{"","O texto diz explicitamente que participação não elimina conflitos.","Diversos grupos são citados.","O texto reconhece que equipamentos podem ser importantes."}));
        return a;
    }

    private Q mathQuestion(int i){
        switch(i){
            case 0:{int price=200+20*r.nextInt(11);int disc=10+5*r.nextInt(4);int d=price*disc/100;int finalV=price-d;return q("Matemática","Porcentagem",null,null,"Uma taxa de inscrição custa R$ "+price+". Durante uma campanha, há desconto de "+disc+"%. Qual é o valor pago, considerando desconto único?",optsMoney(finalV,price-disc,price-d/2,price+d),0,"O desconto é "+disc+"% de "+price+", isto é, R$ "+d+". Subtraindo do valor inicial: R$ "+finalV+".",null);}
            case 1:{int workers=4+r.nextInt(4);int days=12;int twice=workers*2;return q("Matemática","Proporcionalidade inversa",null,null,"Uma equipe de "+workers+" pessoas conclui uma tarefa padronizada em "+days+" dias. Mantendo a mesma produtividade individual e dobrando a equipe para "+twice+" pessoas, qual tempo é esperado?",new String[]{"6 dias","12 dias","24 dias","3 dias"},0,"Ao dobrar o número de trabalhadores, o tempo cai pela metade: 12/2=6 dias.",new String[]{"","Isso ignoraria o aumento da equipe.","Isso trataria a relação como direta.","Reduz o tempo por fator 4, sem justificativa."});}
            case 2:{int a=2+r.nextInt(4),x=3+r.nextInt(5),b=1+r.nextInt(5),y=a*x+b;return q("Matemática","Função afim",null,null,"Uma gráfica cobra uma taxa fixa de R$ "+b+" mais R$ "+a+" por página colorida. Se C(x)="+a+"x+"+b+", qual é o custo de "+x+" páginas?",optsMoney(y,a*x,b*x,y+a),0,"Substituindo x="+x+": C("+x+")="+a+"×"+x+"+"+b+"="+y+".",null);}
            case 3:{int n=2+r.nextInt(4);int sq=n*n;return q("Matemática","Equação do 2º grau",null,null,"Para montar uma região quadrada de área "+sq+" m², o lado x deve satisfazer x²="+sq+". Considerando comprimento positivo, qual é x?",new String[]{n+" m",sq+" m",(n+1)+" m",(sq+n)+" m"},0,"Como x²="+sq+" e comprimento é positivo, x=√"+sq+"="+n+" m.",null);}
            case 4:{int a=3+r.nextInt(4),b=4+r.nextInt(5);int c=(int)Math.round(Math.sqrt(a*a+b*b));if(c*c!=a*a+b*b){a=3;b=4;c=5;}return q("Matemática","Teorema de Pitágoras",null,null,"Uma escada forma um triângulo retângulo com o chão. A distância da base à parede é "+a+" m e a altura alcançada é "+b+" m. Qual é o comprimento da escada?",new String[]{c+" m",(a+b)+" m",(a*b)+" m",(c+2)+" m"},0,"A escada é a hipotenusa: c²="+a+"²+"+b+"², então c="+c+" m.",null);}
            case 5:{int w=6+r.nextInt(5),h=4+r.nextInt(4),area=w*h;return q("Matemática","Área de retângulo",null,null,"Um painel retangular mede "+w+" m por "+h+" m. Um projeto precisa cobrir toda a superfície. Qual é a área mínima a ser coberta?",new String[]{area+" m²",(2*w+2*h)+" m²",(w+h)+" m²",(area*2)+" m²"},0,"Área de retângulo é base×altura: "+w+"×"+h+"="+area+" m².",null);}
            case 6:{int capital=1000;int pct=10;int amount=1210;return q("Matemática","Juros compostos",null,null,"Um valor de R$ 1.000 é aplicado por dois períodos a 10% por período, com capitalização composta. Desconsiderando taxas, qual montante resulta?",new String[]{"R$ 1.210","R$ 1.200","R$ 1.100","R$ 1.020"},0,"No primeiro período: 1000×1,10=1100. No segundo: 1100×1,10=1210. A segunda taxa incide sobre o valor atualizado.",new String[]{"","R$ 1.200 seria a soma linear de 20% sobre o capital inicial, própria de raciocínio de juros simples.","É o valor após apenas um período.","Confunde 10% com adição de R$ 10 por período."});}
            case 7:{int k=2+r.nextInt(4);return q("Matemática","Fatoração",null,null,"A expressão x²+"+(2*k)+"x+"+(k*k)+" representa a área algébrica de um quadrado. Qual fatoração é equivalente?",new String[]{"(x+"+k+")²","(x−"+k+")²","x(x+"+(2*k)+")","(x+"+(k*k)+")²"},0,"É um trinômio quadrado perfeito: x²+2·"+k+"·x+"+k+"²=(x+"+k+")².",null);}
            case 8:{int scale=50000,cm=4+r.nextInt(5);double km=cm*scale/100000.0;String corr=format(km)+" km";return q("Matemática","Escala cartográfica",null,null,"Em um mapa de escala 1:"+scale+", dois pontos estão separados por "+cm+" cm. Qual é aproximadamente a distância real?",new String[]{corr,cm+" km",(cm*5)+" km",format(km/10)+" km"},0,"Cada centímetro representa "+scale+" cm reais. "+cm+"×"+scale+" cm = "+format(cm*scale/100.0)+" m = "+format(km)+" km.",null);}
            default:{int total=30,math=12,science=8,both=5,union=math+science-both;return q("Matemática","Conjuntos",null,null,"Em uma turma de "+total+" estudantes, "+math+" participam de um grupo de matemática, "+science+" de ciências e "+both+" participam dos dois. Quantos estão em pelo menos um dos grupos?",new String[]{String.valueOf(union),String.valueOf(math+science),String.valueOf(both),String.valueOf(total-union)},0,"Pelo princípio da inclusão-exclusão: "+math+"+"+science+"−"+both+"="+union+". Quem está nos dois foi contado duas vezes e deve ser subtraído uma vez.",null);}
        }
    }

    private ArrayList<Q> natureSet(){ArrayList<Q>a=new ArrayList<>();
        a.add(q("Física","Lei de Ohm",null,null,"Um dispositivo de resistência 20 Ω é ligado a uma fonte de 10 V e pode ser tratado como ôhmico. Qual corrente circula?",new String[]{"0,5 A","2 A","200 A","30 A"},0,"I=U/R=10/20=0,5 A.",new String[]{"","2 A resultaria de uma relação numérica incorreta.","Multiplica tensão e resistência.","Soma grandezas de unidades diferentes."}));
        a.add(q("Física","Potência elétrica",null,null,"Um aparelho opera a 100 V e é percorrido por corrente de 2 A. Qual potência elétrica consome nessas condições?",new String[]{"200 W","50 W","102 W","2 W"},0,"P=U·I=100×2=200 W.",null));
        a.add(q("Física","Energia e potência",null,null,"Duas máquinas realizam o mesmo trabalho, mas a máquina A termina em metade do tempo da B. Desprezando perdas, o que se pode afirmar sobre a potência média de A?",new String[]{"É o dobro da de B","É a metade da de B","É igual à de B","É zero"},0,"Potência é trabalho dividido pelo tempo. Mesmo trabalho em metade do tempo implica potência duas vezes maior.",null));
        a.add(q("Química","Isótopos",null,null,"Dois átomos possuem 8 prótons cada, mas um tem 8 nêutrons e outro 10 nêutrons. A relação entre eles é de:",new String[]{"isótopos","isóbaros","isótonos","íons obrigatoriamente"},0,"Mesmo número de prótons significa mesmo elemento; diferente número de nêutrons/massa caracteriza isótopos.",null));
        a.add(q("Química","Separação de misturas",null,null,"Uma amostra contém areia insolúvel em água e sal totalmente dissolvido. Para recuperar separadamente a areia e o sal, uma sequência adequada é:",new String[]{"filtração e depois evaporação/cristalização","somente decantação","destilação antes de adicionar água","peneiração seguida de imantação"},0,"A filtração retém a areia; depois a água pode ser removida para cristalizar o sal dissolvido.",null));
        a.add(q("Química","Transformação química",null,null,"Qual observação fornece evidência mais forte de que ocorreu uma transformação química, e não apenas mudança física?",new String[]{"formação de novas substâncias com propriedades diferentes","gelo derretendo","água evaporando","papel sendo cortado"},0,"Transformação química envolve formação de substâncias novas; fusão, evaporação e corte podem ocorrer sem mudar a identidade química.",null));
        a.add(q("Biologia","Fluxo de energia",null,null,"Em uma cadeia capim → gafanhoto → sapo → cobra, por que a energia disponível tende a diminuir nos níveis tróficos mais altos?",new String[]{"Parte da energia é usada no metabolismo e dissipada como calor em cada nível","A energia é criada apenas pelos predadores","Produtores não armazenam energia","A matéria desaparece completamente a cada transferência"},0,"Organismos usam energia em processos vitais e parte é dissipada como calor; por isso apenas uma fração segue para o próximo nível.",null));
        a.add(q("Biologia","Efeito estufa",null,null,"O efeito estufa natural é importante para a vida, mas sua intensificação preocupa. Qual afirmação distingue corretamente as duas situações?",new String[]{"O efeito natural ajuda a manter temperaturas habitáveis; o aumento de gases-estufa pode elevar a temperatura média","Todo efeito estufa é causado apenas por indústrias modernas","Sem gases-estufa a Terra teria exatamente a mesma temperatura","O aumento de CO₂ sempre resfria a superfície"},0,"O efeito estufa é um processo natural; aumentar a concentração de gases que absorvem radiação infravermelha pode intensificar o aquecimento.",null));
        a.add(q("Biologia","Genótipo e fenótipo",null,null,"Em genética, qual distinção é adequada entre genótipo e fenótipo?",new String[]{"Genótipo é a constituição genética; fenótipo é o conjunto de características observáveis resultantes da interação entre genes e ambiente","Genótipo é apenas aparência; fenótipo é apenas DNA","São sempre sinônimos","Fenótipo nunca sofre influência ambiental"},0,"Genótipo se refere à informação genética; fenótipo é a manifestação observável, que pode depender também do ambiente.",null));
        return a;}

    private ArrayList<Q> humanSet(){ArrayList<Q>a=new ArrayList<>();
        String hc="Um governo europeu dos séculos XVI e XVII aumenta tarifas sobre produtos estrangeiros, concede monopólios comerciais e busca ampliar reservas de metais preciosos.";
        a.add(q("História","Mercantilismo","Fonte histórica simulada",hc,"O conjunto de medidas descrito aproxima-se de qual prática econômica?",new String[]{"mercantilismo","livre-comércio liberal do século XIX","coletivização socialista","economia feudal sem Estado central"},0,"Protecionismo, monopólios e metalismo são práticas frequentemente associadas ao mercantilismo dos Estados modernos.",null));
        a.add(q("História","Colonização portuguesa",null,null,"Na colonização portuguesa da América, a produção açucareira dos séculos XVI e XVII esteve ligada, em grande parte, a qual combinação?",new String[]{"grandes propriedades, trabalho escravizado e produção voltada ao comércio atlântico","pequenas propriedades industriais com trabalho assalariado predominante","ausência de comércio externo","produção urbana baseada em fábricas mecanizadas"},0,"A economia açucareira colonial articulou latifúndio, trabalho escravizado e exportação pelo sistema atlântico.",null));
        a.add(q("História","Reforma Protestante",null,null,"Ao analisar a Reforma Protestante, qual abordagem histórica é mais adequada?",new String[]{"Relacionar críticas religiosas a disputas políticas, sociais e econômicas do período","Explicá-la por uma única causa isolada","Tratà-la como evento ocorrido sem relação com a imprensa e os Estados europeus","Concluir que produziu efeitos idênticos em todos os territórios"},0,"A Reforma envolveu dimensões religiosas, políticas, sociais e econômicas e teve desdobramentos distintos em diferentes regiões.",null));
        a.add(q("História","Expansão marítima",null,null,"Por que a expansão marítima europeia dos séculos XV e XVI não deve ser explicada por um único motivo?",new String[]{"Ela reuniu interesses comerciais, tecnológicos, políticos e religiosos que se combinaram de formas diferentes","Porque não havia interesses econômicos","Porque navegação dispensava conhecimento técnico","Porque todos os reinos tinham exatamente os mesmos recursos"},0,"A expansão resultou da combinação de interesses e condições diversas, não de uma causa única.",null));
        a.add(q("Geografia","Escala cartográfica",null,null,"Ao comparar dois mapas do mesmo território, um na escala 1:25.000 e outro 1:1.000.000, qual tende a mostrar mais detalhes locais?",new String[]{"O de 1:25.000","O de 1:1.000.000","Os dois necessariamente mostram exatamente os mesmos detalhes","Nenhum, pois escala não afeta representação"},0,"A escala 1:25.000 é maior e representa uma área menor com maior possibilidade de detalhamento.",null));
        a.add(q("Geografia","Globalização",null,null,"Uma empresa projeta um produto em um país, compra peças em vários continentes e vende em dezenas de mercados. Qual conceito melhor explica essa organização?",new String[]{"rede produtiva global","autossuficiência local","isolamento econômico","fim dos fluxos internacionais"},0,"A produção distribuída e articulada por diferentes territórios caracteriza redes produtivas globais.",null));
        a.add(q("Geografia","Transição demográfica",null,null,"Um país apresenta queda persistente da mortalidade e, depois, redução da natalidade. Em termos demográficos, esse processo se relaciona principalmente a:",new String[]{"transição demográfica","tectonismo","intemperismo químico","regionalização climática"},0,"A transição demográfica descreve mudanças históricas nas taxas de mortalidade e natalidade associadas à transformação da estrutura populacional.",null));
        a.add(q("Geografia","Estrutura fundiária",null,null,"Em uma região, grande parte da área agrícola está concentrada em poucas propriedades muito extensas, enquanto muitas famílias possuem parcelas pequenas. O dado descreve principalmente:",new String[]{"concentração fundiária","homogeneidade climática","migração pendular","erosão marinha"},0,"A distribuição desigual da terra entre poucas grandes propriedades e muitas pequenas caracteriza concentração fundiária.",null));
        return a;}

    private Q q(String subject,String topic,String title,String context,String prompt,String[] opts,int correct,String explain,String[] wrong){String[] oo=Arrays.copyOf(opts,4);int cc=correct;String[] ww=wrong==null?defaultWrong(oo,cc):Arrays.copyOf(wrong,4);ArrayList<Integer> idx=new ArrayList<>(Arrays.asList(0,1,2,3));Collections.shuffle(idx,r);String[] shuffled=new String[4];String[] sw=new String[4];int newCorrect=0;for(int i=0;i<4;i++){int old=idx.get(i);shuffled[i]=oo[old];sw[i]=ww[old]==null||ww[old].isEmpty()?"Essa alternativa não corresponde aos dados ou ao conceito pedido.":ww[old];if(old==cc)newCorrect=i;}return new Q(subject,topic,title,context,prompt,shuffled,newCorrect,explain,sw);}
    private String[] defaultWrong(String[] opts,int correct){String[] w=new String[4];for(int i=0;i<4;i++)w[i]=i==correct?"":"Essa alternativa não aplica corretamente a relação pedida no enunciado.";return w;}
    private String[] optsMoney(int correct,int a,int b,int c){LinkedHashSet<Integer>s=new LinkedHashSet<>();s.add(correct);s.add(a);s.add(b);s.add(c);int d=10;while(s.size()<4){s.add(correct+d);d+=10;}String[] o=new String[4];int i=0;for(int v:s)o[i++]="R$ "+v;return o;}
    private String format(double v){if(Math.abs(v-Math.rint(v))<1e-9)return String.valueOf((int)Math.rint(v));return String.format(Locale.US,"%.1f",v).replace('.',',');}

    @Override protected void onDestroy(){handler.removeCallbacks(tick);super.onDestroy();}
    static class Q{final String subject,topic,contextTitle,context,prompt;final String[] options,wrong;final int correct;final String explain;Q(String s,String t,String ct,String c,String p,String[] o,int k,String e,String[] w){subject=s;topic=t;contextTitle=ct;context=c;prompt=p;options=o;correct=k;explain=e;wrong=w;}String wrongWhy(int i){if(i<0||i>=wrong.length)return "Questão não respondida.";return wrong[i];}}
}
