package com.cefettrainer.app;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import java.io.InputStream;
import java.util.*;

public class MainActivity extends Activity {
  static final int PICK=101,CAM=102; final Random r=new Random();
  final int NAVY=Color.rgb(13,43,74), BLUE=Color.rgb(28,91,150), GREEN=Color.rgb(34,131,94), RED=Color.rgb(183,61,61), BG=Color.rgb(244,247,250), TEXT=Color.rgb(25,37,49);
  SharedPreferences prefs; String screen="home", mode="full"; ArrayList<Q> qs=new ArrayList<>(); ArrayList<RadioGroup> groups=new ArrayList<>();
  TextRecognizer recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS); ImageView preview; EditText ocrEdit,essayEdit; TextView ocrStatus; RadioGroup ocrMode; Bitmap lastBitmap; String theme;
  final String[] themes={"Os impactos do uso excessivo da tecnologia nos jovens brasileiros","A importância do engajamento do jovem com questões sociais do seu tempo","O papel da leitura na formação dos jovens","Desafios para combater a desinformação entre adolescentes","Como equilibrar tecnologia e concentração na vida escolar","O papel da escola na formação de leitores críticos","Caminhos para ampliar a participação dos jovens na comunidade","A preservação dos espaços públicos como responsabilidade coletiva"};
  final String[][] topics={{"Português","Interpretação e inferência","Coesão e conectivos","Pontuação","Concordância","Crase","Figuras de linguagem","Gêneros textuais"},{"Matemática","Porcentagem","Razão e proporção","Equações","Função do 1º grau","Geometria","Probabilidade","Média","Unidades"},{"Física","Movimento","Energia","Calor","Óptica","Eletricidade"},{"Química","Matéria e propriedades","Misturas","Transformações químicas","Átomos","Tabela periódica"},{"Biologia","Célula","Ecologia","Genética","Corpo humano","Evolução"},{"História","Brasil Colônia","Império","República","Revoluções","Industrialização"},{"Geografia","Globalização","Urbanização","Cartografia","População","Clima","Meio ambiente"}};

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);prefs=getSharedPreferences("cefet_trainer_v5",MODE_PRIVATE);home();}
  TextView tv(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(TEXT);v.setPadding(8,8,8,8);if(bold)v.setTypeface(null,1);return v;}
  Button btn(String s,int color,View.OnClickListener f){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(color));b.setOnClickListener(f);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,6,0,6);b.setLayoutParams(p);return b;}
  LinearLayout root(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(18,18,18,30);x.setBackgroundColor(BG);return x;}
  ScrollView page(LinearLayout x){ScrollView s=new ScrollView(this);s.addView(x);return s;}
  void back(LinearLayout x,String title){x.addView(btn("← Início",NAVY,v->home()));x.addView(tv(title,26,true));}
  void home(){screen="home";LinearLayout x=root();x.addView(tv("CEFET Trainer",31,true));x.addView(tv("Treino para o CEFET/RJ",16,false));int ready=prefs.getInt("ready",0),points=prefs.getInt("points",0);x.addView(tv("Prontidão: "+ready+"%   •   "+points+" pontos",18,true));ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(100);pb.setProgress(ready);x.addView(pb,new LinearLayout.LayoutParams(-1,28));if(ready>=100)x.addView(tv("Você atingiu 100% de prontidão. Continue treinando para manter o nível.",15,true));x.addView(btn("Gerar simulado diferente",BLUE,v->startExam("full",null)));x.addView(btn("Estudar por matéria",NAVY,v->study()));x.addView(btn("Provas reais e gabaritos",GREEN,v->realExams()));x.addView(btn("Redação por foto / OCR",Color.rgb(128,81,156),v->essay()));x.addView(btn("Progresso",Color.rgb(93,105,115),v->progress()));setContentView(page(x));}

  void startExam(String m,String subject){mode=m;qs.clear();groups.clear();if("full".equals(m))genFull();else genSubject(subject,10);showExam(subject);}
  void genFull(){for(int i=0;i<10;i++)qs.add(genPt(i));for(int i=0;i<10;i++)qs.add(genMath(i));ArrayList<Q> nat=naturePool();Collections.shuffle(nat,r);qs.addAll(nat.subList(0,5));ArrayList<Q> hum=humanPool();Collections.shuffle(hum,r);qs.addAll(hum.subList(0,5));Collections.shuffle(qs.subList(20,30),r);}
  void genSubject(String s,int n){for(int i=0;i<n;i++){if("Matemática".equals(s))qs.add(genMath(i));else if("Português".equals(s))qs.add(genPt(i));else {ArrayList<Q> p=(s.equals("Física")||s.equals("Química")||s.equals("Biologia"))?naturePool():humanPool();ArrayList<Q> f=new ArrayList<>();for(Q q:p)if(q.subject.equals(s))f.add(q);if(f.isEmpty())f=p;qs.add(f.get(r.nextInt(f.size())).copy("_"+i+"_"+r.nextInt(99999)));}}}
  void showExam(String subject){screen="exam";LinearLayout x=root();back(x,"full".equals(mode)?"Simulado completo — 30 questões":"Treino: "+subject);x.addView(tv("Responda tudo. O gabarito só aparece depois de finalizar.",14,false));int k=1;for(Q q:qs){x.addView(tv(k+". ["+q.subject+"] "+q.prompt,16,true));RadioGroup g=new RadioGroup(this);g.setOrientation(RadioGroup.VERTICAL);for(int j=0;j<4;j++){RadioButton rb=new RadioButton(this);rb.setId(1000+k*10+j);rb.setText((char)('A'+j)+") "+q.opts[j]);rb.setTextSize(15);g.addView(rb);}groups.add(g);x.addView(g);k++;}x.addView(btn("Finalizar e corrigir",GREEN,v->finishExam()));setContentView(page(x));}
  void finishExam(){for(RadioGroup g:groups)if(g.getCheckedRadioButtonId()==-1){Toast.makeText(this,"Responda todas as questões antes de corrigir.",Toast.LENGTH_LONG).show();return;}int hit=0;for(int i=0;i<qs.size();i++){int id=groups.get(i).getCheckedRadioButtonId();int chosen=(id-1000-(i+1)*10);if(chosen==qs.get(i).correct)hit++;}int add=hit*10;prefs.edit().putInt("points",prefs.getInt("points",0)+add).putInt("tests",prefs.getInt("tests",0)+1).apply();if("full".equals(mode)&&hit==qs.size()){int nr=Math.min(100,prefs.getInt("ready",0)+5);prefs.edit().putInt("ready",nr).putInt("perfect",prefs.getInt("perfect",0)+1).apply();}result(hit);}
  void result(int hit){screen="result";LinearLayout x=root();back(x,"Resultado");int pct=(int)Math.round(hit*100.0/qs.size());x.addView(tv(hit+"/"+qs.size()+" acertos — "+pct+"%",25,true));for(int i=0;i<qs.size();i++){Q q=qs.get(i);int chosen=groups.get(i).getCheckedRadioButtonId()-1000-(i+1)*10;boolean ok=chosen==q.correct;x.addView(tv((i+1)+". "+(ok?"✓":"✗")+" "+q.prompt,15,true));x.addView(tv("Sua resposta: "+(char)('A'+chosen)+"   |   Gabarito: "+(char)('A'+q.correct),14,false));x.addView(tv("Explicação: "+q.explain,13,false));}x.addView(btn("Gerar outra prova",BLUE,v->startExam(mode,"full".equals(mode)?null:qs.get(0).subject)));setContentView(page(x));}

  void study(){screen="study";LinearLayout x=root();back(x,"Estudar por matéria");for(String[] a:topics){String s=a[0];x.addView(btn(s,BLUE,v->subjectPage(s)));}setContentView(page(x));}
  void subjectPage(String s){LinearLayout x=root();back(x,s);for(String[] a:topics)if(a[0].equals(s)){for(int i=1;i<a.length;i++)x.addView(tv("• "+a[i],16,false));break;}x.addView(btn("Treinar 10 questões de "+s,GREEN,v->startExam("subject",s)));setContentView(page(x));}

  void realExams(){screen="real";LinearLayout x=root();back(x,"Provas reais e gabaritos");x.addView(tv("Use os gabaritos para corrigir os cadernos oficiais que você já possui.",14,false));examCard(x,2023,40,"BCDBCDAABABABCDDCBADDCBAACABBADCCBACABBA");examCard(x,2024,30,"BCACBDBADCDACABCABDCCADBDAACDB");examCard(x,2025,30,"ACBACDBDACBDCBACCADDACDBDBACBD");examCard(x,2026,30,"DBADCBDCACDABDCCAABDCDCABBCDBC");setContentView(page(x));}
  void examCard(LinearLayout x,int year,int n,String key){x.addView(tv("CEFET/RJ "+year+" — "+n+" questões",20,true));x.addView(tv("Gabarito: "+spacedKey(key),14,false));}
  String spacedKey(String k){StringBuilder s=new StringBuilder();for(int i=0;i<k.length();i++){if(i>0)s.append(i%10==0?"\n":"  ");s.append(i+1).append(':').append(k.charAt(i));}return s.toString();}

  void progress(){screen="progress";LinearLayout x=root();back(x,"Progresso");x.addView(tv(prefs.getInt("ready",0)+"% de prontidão",28,true));x.addView(tv(prefs.getInt("points",0)+" pontos",20,true));x.addView(tv(prefs.getInt("tests",0)+" provas/treinos concluídos",16,false));x.addView(tv(prefs.getInt("perfect",0)+" simulados perfeitos",16,false));x.addView(tv("Cada simulado completo com 100% adiciona 5% à prontidão. A pontuação continua aumentando mesmo depois de 100%.",14,false));x.addView(btn("Zerar progresso",RED,v->{prefs.edit().clear().apply();progress();}));setContentView(page(x));}

  void essay(){screen="essay";theme=themes[r.nextInt(themes.length)];LinearLayout x=root();back(x,"Redação — foto e OCR");x.addView(tv("Tema",15,true));TextView th=tv(theme,19,true);x.addView(th);x.addView(btn("Gerar outro tema",BLUE,v->{theme=themes[r.nextInt(themes.length)];th.setText(theme);}));x.addView(tv("Leitor de caligrafia",18,true));ocrMode=new RadioGroup(this);RadioButton a=new RadioButton(this),d=new RadioButton(this);a.setText("Automático");a.setId(1);d.setText("Caligrafia difícil / disgrafia");d.setId(2);ocrMode.addView(a);ocrMode.addView(d);ocrMode.check(2);x.addView(ocrMode);x.addView(btn("Escolher foto",NAVY,v->pickImage()));x.addView(btn("Tirar foto",NAVY,v->takePhoto()));preview=new ImageView(this);preview.setAdjustViewBounds(true);preview.setMaxHeight(700);x.addView(preview,new LinearLayout.LayoutParams(-1,-2));ocrStatus=tv("Envie uma imagem para começar.",14,false);x.addView(ocrStatus);x.addView(tv("Texto reconhecido — você pode corrigir erros do leitor",15,true));ocrEdit=new EditText(this);ocrEdit.setMinLines(8);ocrEdit.setGravity(Gravity.TOP);ocrEdit.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);x.addView(ocrEdit,new LinearLayout.LayoutParams(-1,-2));x.addView(btn("Organizar espaços, maiúsculas e pontuação",GREEN,v->{String cleaned=cleanup(ocrEdit.getText().toString());ocrEdit.setText(cleaned);essayEdit.setText(cleaned);}));x.addView(tv("Redação para avaliação",15,true));essayEdit=new EditText(this);essayEdit.setMinLines(10);essayEdit.setGravity(Gravity.TOP);essayEdit.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);x.addView(essayEdit,new LinearLayout.LayoutParams(-1,-2));x.addView(btn("Avaliar redação",Color.rgb(128,81,156),v->scoreEssay()));setContentView(page(x));}
  void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);}
  void takePhoto(){Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);try{startActivityForResult(i,CAM);}catch(Exception e){Toast.makeText(this,"Câmera não disponível.",Toast.LENGTH_LONG).show();}}
  @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null)return;try{Bitmap b=null;if(req==PICK&&data.getData()!=null){Uri u=data.getData();try(InputStream in=getContentResolver().openInputStream(u)){b=BitmapFactory.decodeStream(in);}}else if(req==CAM&&data.getExtras()!=null){Object o=data.getExtras().get("data");if(o instanceof Bitmap)b=(Bitmap)o;}if(b!=null){lastBitmap=limit(b,2200);preview.setImageBitmap(lastBitmap);runOcr(lastBitmap,ocrMode.getCheckedRadioButtonId()==2);}}catch(Exception e){ocrStatus.setText("Não consegui ler a imagem: "+e.getMessage());}}
  Bitmap limit(Bitmap b,int max){int w=b.getWidth(),h=b.getHeight();if(Math.max(w,h)<=max)return b;float sc=max/(float)Math.max(w,h);return Bitmap.createScaledBitmap(b,Math.max(1,(int)(w*sc)),Math.max(1,(int)(h*sc)),true);}
  Bitmap contrast(Bitmap src,boolean threshold){Bitmap out=Bitmap.createBitmap(src.getWidth(),src.getHeight(),Bitmap.Config.ARGB_8888);int[] p=new int[src.getWidth()*src.getHeight()];src.getPixels(p,0,src.getWidth(),0,0,src.getWidth(),src.getHeight());for(int i=0;i<p.length;i++){int c=p[i],g=(int)(0.299*Color.red(c)+0.587*Color.green(c)+0.114*Color.blue(c));g=Math.max(0,Math.min(255,(int)((g-128)*1.7+128)));if(threshold)g=g>165?255:0;p[i]=Color.rgb(g,g,g);}out.setPixels(p,0,src.getWidth(),0,0,src.getWidth(),src.getHeight());return out;}
  void runOcr(Bitmap b,boolean hard){ocrStatus.setText("Lendo a redação...");ArrayList<Bitmap> variants=new ArrayList<>();variants.add(b);if(hard){variants.add(contrast(b,false));variants.add(contrast(b,true));}ArrayList<String> texts=new ArrayList<>();ocrSeq(variants,0,texts);}
  void ocrSeq(ArrayList<Bitmap> bs,int i,ArrayList<String> texts){if(i>=bs.size()){String best="";for(String s:texts)if(scoreOcr(s)>scoreOcr(best))best=s;ocrEdit.setText(best);essayEdit.setText(best);ocrStatus.setText("Leitura concluída em "+texts.size()+" tentativa(s). Revise palavras que o OCR possa ter interpretado errado.");return;}recognizer.process(InputImage.fromBitmap(bs.get(i),0)).addOnSuccessListener(t->{texts.add(t.getText());ocrSeq(bs,i+1,texts);}).addOnFailureListener(e->{texts.add("");ocrSeq(bs,i+1,texts);});}
  int scoreOcr(String s){if(s==null)return 0;int words=s.trim().isEmpty()?0:s.trim().split("\\s+").length;int letters=0;for(char c:s.toCharArray())if(Character.isLetter(c))letters++;return words*5+letters;}
  String cleanup(String s){if(s==null)return "";s=s.replace("\r","").replaceAll("[ \\t]+"," ").replaceAll(" ?\\n ?","\n").replaceAll("\\n{3,}","\n\n").trim();String[] ps=s.split("\\n");StringBuilder out=new StringBuilder();for(String p:ps){p=p.trim();if(p.isEmpty()){if(out.length()>0)out.append("\n");continue;}p=cap(p);p=p.replaceAll("(?i)^(porém|portanto|além disso|assim|contudo|entretanto|desse modo|por isso)\\s+","$1, ");if(!p.matches(".*[.!?;:]$"))p+=".";if(out.length()>0)out.append("\n");out.append(p);}String z=out.toString();StringBuilder f=new StringBuilder();boolean cap=true;for(int i=0;i<z.length();i++){char c=z.charAt(i);if(cap&&Character.isLetter(c)){c=Character.toUpperCase(c);cap=false;}f.append(c);if(c=='.'||c=='!'||c=='?'||c=='\n')cap=true;}return f.toString();}
  String cap(String s){if(s.isEmpty())return s;for(int i=0;i<s.length();i++)if(Character.isLetter(s.charAt(i)))return s.substring(0,i)+Character.toUpperCase(s.charAt(i))+s.substring(i+1);return s;}
  void scoreEssay(){String s=essayEdit.getText().toString().trim();if(s.isEmpty()){Toast.makeText(this,"Coloque o texto da redação primeiro.",Toast.LENGTH_LONG).show();return;}String[] w=s.split("\\s+");int words=w.length,paragraphs=Math.max(1,s.split("\\n\\s*\\n|\\n").length),punct=count(s,'.')+count(s,',')+count(s,';')+count(s,':'),conn=0;String low=s.toLowerCase(Locale.ROOT);for(String c:new String[]{"portanto","porém","além disso","assim","contudo","entretanto","porque","desse modo","por isso"})if(low.contains(c))conn++;int score=0;score+=Math.min(30,(int)(words/5.0));score+=Math.min(20,paragraphs*5);score+=Math.min(20,punct*2);score+=Math.min(20,conn*5);if(words>=120)score+=10;score=Math.min(100,score);new AlertDialog.Builder(this).setTitle("Avaliação de treino: "+score+"/100").setMessage("Palavras: "+words+"\nParágrafos detectados: "+paragraphs+"\nConectivos encontrados: "+conn+"\nPontuação detectada: "+punct+"\n\nEsta correção não reescreve sua gramática. Ela mede estrutura, desenvolvimento, conectivos e pontuação como treino.").setPositiveButton("OK",null).show();prefs.edit().putInt("points",prefs.getInt("points",0)+Math.max(1,score/10)).apply();}
  int count(String s,char c){int n=0;for(char x:s.toCharArray())if(x==c)n++;return n;}

  Q genMath(int i){int t=i%10,a,b,c,ans;switch(t){case 0:a=50+r.nextInt(451);b=(1+r.nextInt(8))*5;ans=a*b/100;return numQ("Matemática","Quanto é "+b+"% de "+a+"?",ans,"Porcentagem = valor × taxa ÷ 100.");case 1:a=2+r.nextInt(8);b=2+r.nextInt(8);c=2+r.nextInt(8);ans=b*c;return numQ("Matemática","Se "+a+" cadernos custam R$ "+(a*b)+", quanto custam "+c+" cadernos pelo mesmo preço unitário?",ans,"Preço unitário = "+b+"; multiplique por "+c+".");case 2:a=2+r.nextInt(8);b=1+r.nextInt(12);ans=3+r.nextInt(20);c=a*ans+b;return numQ("Matemática","Resolva: "+a+"x + "+b+" = "+c+".",ans,"Isole x: ("+c+"−"+b+")÷"+a+".");case 3:a=3+r.nextInt(15);b=3+r.nextInt(15);ans=a*b;return numQ("Matemática","Um retângulo mede "+a+" m por "+b+" m. Qual é sua área?",ans,"Área do retângulo = base × altura.");case 4:int m=3+r.nextInt(5),n=4+r.nextInt(6);a=m*m-n*n;if(a==0)a=3;b=2*m*n;c=m*m+n*n;ans=c;return numQ("Matemática","Um triângulo retângulo tem catetos "+Math.abs(a)+" e "+Math.abs(b)+". Qual é a hipotenusa?",ans,"Use Pitágoras: h²=a²+b².");case 5:a=2+r.nextInt(10);b=2+r.nextInt(10);c=2+r.nextInt(10);ans=(a+b+c);int mean=ans;return numQ("Matemática","A média de 3 números é "+mean+". Se dois deles são "+a+" e "+b+", qual é o terceiro?",3*mean-a-b,"Soma total = média × 3.");case 6:a=1+r.nextInt(5);b=a+2+r.nextInt(6);return numQ("Matemática","Em uma caixa há "+a+" bolas azuis e "+(b-a)+" vermelhas. Qual a probabilidade, em %, de tirar uma azul?",(int)Math.round(100.0*a/b),"Probabilidade = casos favoráveis ÷ total × 100.");case 7:a=1+r.nextInt(9);ans=a*1000;return numQ("Matemática",a+" km correspondem a quantos metros?",ans,"1 km = 1000 m.");case 8:a=(2+r.nextInt(9))*50;b=(1+r.nextInt(5))*10;ans=a-(a*b/100);return numQ("Matemática","Um produto custa R$ "+a+" e recebe desconto de "+b+"%. Qual o novo preço?",ans,"Calcule o desconto e subtraia do preço inicial.");default:a=2+r.nextInt(6);b=r.nextInt(10);c=1+r.nextInt(10);ans=a*c+b;return numQ("Matemática","Na função f(x)="+a+"x+"+b+", quanto vale f("+c+")?",ans,"Substitua x por "+c+".");}}
  Q numQ(String subject,String prompt,int ans,String exp){LinkedHashSet<Integer> set=new LinkedHashSet<>();set.add(ans);while(set.size()<4){int d=1+r.nextInt(Math.max(4,Math.abs(ans)/4+3));set.add(Math.max(0,ans+(r.nextBoolean()?d:-d)));}ArrayList<Integer> vals=new ArrayList<>(set);Collections.shuffle(vals,r);String[] o=new String[4];int ci=0;for(int i=0;i<4;i++){o[i]=String.valueOf(vals.get(i));if(vals.get(i)==ans)ci=i;}return new Q(UUID.randomUUID().toString(),subject,prompt,o,ci,exp);}
  Q genPt(int i){ArrayList<Q> p=ptPool();Q q=p.get((i+r.nextInt(p.size()))%p.size());return q.copy("_"+UUID.randomUUID());}
  ArrayList<Q> ptPool(){ArrayList<Q> p=new ArrayList<>();p.add(q("Português","Em 'Embora estivesse cansado, continuou estudando', a palavra 'embora' indica:",new String[]{"causa","concessão","conclusão","explicação"},1,"'Embora' introduz ideia concessiva."));p.add(q("Português","Assinale a alternativa com uso correto da crase:",new String[]{"Fui à escola cedo.","Entreguei à João.","Cheguei à pé.","Vi à professora ontem."},0,"Há crase em 'à escola' pela fusão de a + a."));p.add(q("Português","Em 'O vento cantava entre as árvores', ocorre:",new String[]{"metáfora","personificação","hipérbole","eufemismo"},1,"Atribui-se ação humana ao vento."));p.add(q("Português","Qual conectivo exprime conclusão?",new String[]{"porque","porém","portanto","embora"},2,"'Portanto' introduz conclusão."));p.add(q("Português","Em um texto argumentativo, a tese é:",new String[]{"o título apenas","a posição central defendida","qualquer exemplo","a última palavra"},1,"Tese é a ideia central defendida."));p.add(q("Português","Assinale a frase com concordância adequada:",new String[]{"Houveram problemas.","Fazem dois anos.","Existem boas razões.","Deve haverem soluções."},2,"O verbo existir concorda com 'boas razões'."));p.add(q("Português","A principal função de um conectivo é:",new String[]{"ligar ideias e explicitar relações","aumentar o tamanho do texto","substituir todo verbo","criar rimas"},0,"Conectivos articulam ideias."));p.add(q("Português","Uma inferência de leitura é:",new String[]{"copiar uma frase","concluir algo apoiado em pistas do texto","ignorar o contexto","contar as linhas"},1,"Inferir é concluir a partir de pistas."));p.add(q("Português","Em 'Ele estudou muito; por isso, melhorou o desempenho', 'por isso' expressa:",new String[]{"oposição","consequência","condição","comparação"},1,"'Por isso' introduz consequência."));p.add(q("Português","Qual frase está pontuada de modo mais adequado?",new String[]{"Maria porém chegou cedo.","Maria, porém, chegou cedo.","Maria porém, chegou cedo.","Maria, porém chegou cedo."},1,"Conectivo intercalado fica entre vírgulas."));p.add(q("Português","Um artigo de opinião costuma apresentar:",new String[]{"apenas números","uma posição defendida com argumentos","somente falas de personagens","instruções de montagem"},1,"O gênero defende um ponto de vista."));p.add(q("Português","Em 'A cidade acordou triste', a expressão é exemplo de:",new String[]{"personificação","onomatopeia","pleonasmo","antítese"},0,"A cidade recebe característica humana."));return p;}
  ArrayList<Q> naturePool(){ArrayList<Q> p=new ArrayList<>();p.add(q("Física","Um carro percorre 120 km em 2 h. Sua velocidade média é:",new String[]{"30 km/h","60 km/h","120 km/h","240 km/h"},1,"v=distância/tempo=60 km/h."));p.add(q("Física","A unidade de energia no SI é:",new String[]{"watt","joule","pascal","metro"},1,"Energia é medida em joules."));p.add(q("Física","Em um espelho plano, a imagem é:",new String[]{"real e invertida","virtual e direita","sempre maior","sempre menor"},1,"Espelho plano forma imagem virtual e direita."));p.add(q("Física","Corrente elétrica corresponde ao movimento ordenado de:",new String[]{"cargas elétricas","átomos neutros apenas","ondas sonoras","fótons apenas"},0,"Corrente é fluxo ordenado de cargas."));p.add(q("Química","Uma mistura de água e óleo é:",new String[]{"homogênea","heterogênea","substância pura","elemento químico"},1,"Há mais de uma fase visível."));p.add(q("Química","O número atômico identifica a quantidade de:",new String[]{"prótons","nêutrons apenas","moléculas","ligações"},0,"Número atômico = prótons."));p.add(q("Química","Derreter gelo é uma transformação:",new String[]{"nuclear","física","química irreversível","biológica"},1,"Muda o estado físico sem formar nova substância."));p.add(q("Química","Uma solução com pH menor que 7 é, em geral:",new String[]{"ácida","básica","neutra","metálica"},0,"pH abaixo de 7 indica acidez."));p.add(q("Biologia","A organela associada à produção de ATP é:",new String[]{"mitocôndria","ribossomo","lisossomo","centríolo"},0,"Mitocôndrias participam da respiração celular."));p.add(q("Biologia","Produtores em uma cadeia alimentar são geralmente:",new String[]{"plantas e algas","carnívoros","decompositores apenas","vírus"},0,"Produtores realizam fotossíntese."));p.add(q("Biologia","O material genético presente nos cromossomos é principalmente:",new String[]{"DNA","glicose","amido","lipídio"},0,"Cromossomos são formados principalmente por DNA e proteínas."));p.add(q("Biologia","A seleção natural é um mecanismo relacionado à:",new String[]{"evolução","digestão","evaporação","combustão"},0,"Seleção natural é mecanismo evolutivo."));return p;}
  ArrayList<Q> humanPool(){ArrayList<Q> p=new ArrayList<>();p.add(q("História","A Independência do Brasil foi proclamada em:",new String[]{"1500","1789","1822","1889"},2,"A independência ocorreu em 1822."));p.add(q("História","A Lei Áurea, de 1888, está ligada à:",new String[]{"abolição da escravidão","proclamação da República","independência","criação de Brasília"},0,"A Lei Áurea aboliu legalmente a escravidão."));p.add(q("História","A Proclamação da República no Brasil ocorreu em:",new String[]{"1822","1888","1889","1930"},2,"A República foi proclamada em 1889."));p.add(q("História","A Revolução Industrial começou primeiro na:",new String[]{"Inglaterra","Rússia","Brasil","China"},0,"O pioneirismo industrial foi britânico."));p.add(q("Geografia","Escala cartográfica relaciona:",new String[]{"distância no mapa e distância real","chuva e temperatura","população e renda","latitude e idioma"},0,"A escala compara medida representada e real."));p.add(q("Geografia","Urbanização significa aumento da:",new String[]{"população urbana","área de oceanos","quantidade de continentes","duração do dia"},0,"Urbanização é crescimento relativo/absoluto da população urbana."));p.add(q("Geografia","Latitude é medida a partir da linha do:",new String[]{"Equador","Greenwich","Trópico de Capricórnio apenas","Meridiano 180"},0,"Latitude tem como referência o Equador."));p.add(q("Geografia","Globalização intensifica principalmente:",new String[]{"fluxos de mercadorias, capitais e informação","isolamento absoluto","fim do comércio","desaparecimento das cidades"},0,"Globalização amplia conexões e fluxos."));p.add(q("Geografia","O efeito estufa natural é importante porque:",new String[]{"mantém temperatura compatível com a vida","impede toda chuva","elimina a atmosfera","faz a Terra congelar"},0,"Sem o efeito estufa natural a Terra seria muito mais fria."));p.add(q("História","Cidadania envolve:",new String[]{"direitos e deveres na sociedade","apenas pagar impostos","não participar de decisões","somente votar"},0,"Cidadania envolve direitos, deveres e participação."));return p;}
  Q q(String s,String p,String[] o,int c,String e){return new Q(UUID.randomUUID().toString(),s,p,o,c,e);}
  static class Q{String id,subject,prompt,explain;String[] opts;int correct;Q(String i,String s,String p,String[] o,int c,String e){id=i;subject=s;prompt=p;opts=o;correct=c;explain=e;}Q copy(String x){return new Q(id+x,subject,prompt,opts.clone(),correct,explain);}}
  @Override public void onBackPressed(){if("home".equals(screen))super.onBackPressed();else home();}
  @Override protected void onDestroy(){recognizer.close();super.onDestroy();}
}
