package com.cefettrainer.app;

import java.util.*;

/** Conteúdo complementar do Remaster: amplia o tutor para tópicos avançados do programa. */
public final class StudyCatalogExtra {
    private StudyCatalogExtra() {}

    public static LinkedHashMap<String, StudyCatalog.Node> create() {
        LinkedHashMap<String, StudyCatalog.Node> m = new LinkedHashMap<>();

        // ================= PORTUGUÊS =================
        add(m, n("p_adverbio","Português","Advérbio e circunstância",2,
                "Advérbio modifica verbo, adjetivo ou outro advérbio e costuma indicar circunstâncias como tempo, modo, lugar, intensidade, negação ou afirmação.",
                "ADVÉRBIO responde muitas vezes: quando? onde? como? quanto?",
                "tempo = ontem, hoje, cedo\nmodo = bem, rapidamente\nlugar = aqui, longe\nintensidade = muito, pouco\nnegação = não",
                "Em 'A candidata respondeu muito rapidamente', 'rapidamente' modifica o verbo 'respondeu'; 'muito' intensifica o advérbio 'rapidamente'. Advérbios tendem a ser invariáveis: 'elas chegaram cedo', não 'cedas'.",
                "'O texto é bastante claro.' 'claro' é adjetivo; 'bastante' intensifica essa característica e funciona como advérbio.",
                "Contraexemplo: chamar toda palavra terminada em -mente de adjetivo. 'cuidadosamente' normalmente é advérbio.",
                "Erro comum: identificar a classe sem dizer qual palavra ela modifica.",
                new String[]{"p_adjetivo","p_verbo"},
                q("Em 'Os estudantes chegaram extremamente cedo', o termo 'extremamente' modifica:",1,
                        "estudantes","É substantivo e não recebe a intensidade expressa por 'extremamente'.",null,
                        "cedo","Correto: 'extremamente' intensifica o advérbio 'cedo'.",null,
                        "chegaram diretamente","O modo/tempo da chegada é expresso pelo grupo, mas sintaticamente 'extremamente' intensifica 'cedo'.","p_verbo",
                        "os","Artigo não é o alvo da modificação.","p_artigo"),
                q("Qual frase usa 'meio' como advérbio invariável?",2,
                        "Comprei meio quilo de arroz.","Aqui 'meio' indica metade e funciona como numeral/adjetivo conforme análise.",null,
                        "As meias estavam molhadas.","'meias' é substantivo.",null,
                        "As portas ficaram meio abertas.","Correto: 'meio' significa 'um pouco' e permanece invariável.",null,
                        "Usei duas meias novas.","Substantivo, não advérbio.",null)));

        add(m, n("p_preposicao","Português","Preposição e relação entre termos",2,
                "Preposição liga palavras e estabelece relações de sentido como origem, destino, causa, posse, matéria, assunto ou meio.",
                "PREPOSIÇÃO = ponte entre termos.",
                "a, ante, após, até, com, contra, de, desde, em, entre, para, perante, por, sem, sob, sobre...\nregência = relação em que uma palavra exige/comanda complemento",
                "Em 'livro de História', 'de' liga livro a História. Em 'viajou para Recife', 'para' indica destino. O sentido nasce da relação, não da preposição isolada.",
                "'Morreu de fome' e 'mesa de madeira' usam a mesma preposição, mas com relações diferentes: causa e matéria.",
                "Contraexemplo: decorar que 'de' sempre indica posse. O contexto decide.",
                "Erro comum: procurar apenas a lista de preposições sem interpretar a relação semântica.",
                new String[]{"p_substantivo","p_verbo"},
                q("Em 'O relatório sobre energia foi entregue ao professor', 'sobre' indica principalmente:",3,
                        "posse","Não mostra quem possui o relatório.",null,
                        "origem","Não indica de onde veio.",null,
                        "instrumento","Não indica meio de execução.",null,
                        "assunto","Correto: o relatório trata de energia.",null),
                q("Em 'A ponte foi interditada por segurança', a expressão introduzida por 'por' indica principalmente:",0,
                        "motivo/finalidade de proteção","Correto: a interdição ocorreu visando segurança.",null,
                        "matéria de que a ponte é feita","Nada indica material.",null,
                        "lugar","Não há localização.",null,
                        "posse","Não há relação possessiva.",null)));

        add(m, n("p_pontuacao","Português","Pontuação e organização do sentido",2,
                "Pontuação organiza a estrutura do texto e pode alterar sentido. Vírgula não significa simplesmente 'pausa para respirar'.",
                "PONTUAÇÃO marca relações sintáticas e discursivas.",
                "vírgula = separação de elementos/orações em usos específicos\ndois-pontos = introdução de explicação, enumeração ou fala\nponto e vírgula = separação intermediária\ntravessão = destaque, fala, intercalação",
                "'Não, espere.' é uma ordem para esperar. 'Não espere.' é uma ordem para não esperar. A vírgula muda a relação entre 'não' e o verbo.",
                "Em regra geral, não se separa sujeito do verbo por vírgula: 'Os alunos da turma, chegaram' é inadequado nesse uso básico.",
                "Contraexemplo: colocar vírgula sempre que a frase fica longa. Comprimento não determina a regra.",
                "Erro comum: pontuar pela respiração e ignorar a estrutura da oração.",
                new String[]{"p_sujeito","p_predicado","p_conectivos"},
                q("Qual opção evita separar sujeito e verbo indevidamente?",1,
                        "Os candidatos do turno da manhã, chegaram cedo.","A vírgula separa o sujeito longo de seu verbo sem motivo.","p_sujeito",
                        "Os candidatos do turno da manhã chegaram cedo.","Correto.",null,
                        "Os candidatos, do turno da manhã chegaram cedo.","A vírgula corta a ligação interna do grupo nominal nesse contexto.","p_substantivo",
                        "Os, candidatos do turno da manhã chegaram cedo.","Artigo e substantivo não devem ser separados assim.","p_artigo"),
                q("Compare 'Vamos comer, crianças.' e 'Vamos comer crianças.' A vírgula da primeira frase:",2,
                        "não produz nenhuma diferença","Produz diferença decisiva.",null,
                        "transforma 'comer' em substantivo","'comer' continua verbo.","p_verbo",
                        "marca o vocativo e evita que 'crianças' seja lido como objeto de comer","Correto.",null,
                        "indica plural do verbo","Número verbal não é função da vírgula.","p_numero")));

        add(m, n("p_crase","Português","Crase: fusão de dois 'a'",3,
                "Crase ocorre quando a preposição a se encontra com artigo feminino a/as ou com certos demonstrativos iniciados por a. O acento grave marca essa fusão.",
                "CRASE = a (preposição) + a (artigo) → à.",
                "regência = palavra anterior exige preposição a\nartigo feminino = a/as antes do nome\nteste do masculino = quando possível, trocar por termo masculino e observar 'ao'",
                "'Vou à escola': quem vai, vai a algum lugar; 'escola' admite artigo 'a'. a+a=à. 'Vou a pé': 'pé' é masculino e não há artigo feminino, então não há crase.",
                "Teste: 'Referi-me à professora' → 'Referi-me ao professor'. O aparecimento de 'ao' ajuda a confirmar a fusão.",
                "Contraexemplo: colocar crase antes de todo substantivo feminino. É preciso haver preposição a e artigo/demonstrativo compatível.",
                "Erro comum: usar crase antes de verbo: 'começou à estudar'. Verbos não recebem artigo feminino nessa construção.",
                new String[]{"p_artigo","p_preposicao"},
                q("Qual frase usa crase adequadamente?",0,
                        "Entreguei o documento à diretora.","Correto: entregar algo a alguém + a diretora → à diretora.",null,
                        "Começou à estudar cedo.","Antes de verbo não ocorre artigo feminino nessa construção.","p_verbo",
                        "Fui à pé.","A expressão é 'a pé', sem artigo feminino.",null,
                        "Cheguei à Recife.","Nomes de cidade podem ou não admitir artigo; 'Recife' normalmente aparece sem artigo nessa construção padrão: 'a Recife'.",null),
                q("Em 'A pesquisa se refere ___ condições de trabalho', qual forma completa a frase?",2,
                        "a as","A fusão deve ser marcada por crase.",null,
                        "a","O verbo exige preposição e 'condições' vem com artigo plural; falta a fusão.","p_artigo",
                        "às","Correto: refere-se a + as condições = às condições.",null,
                        "á","Esse acento não representa crase.",null)));

        add(m, n("p_denotacao","Português","Sentido literal, figurado, denotação e conotação",2,
                "Denotação é uso mais literal e convencional da palavra. Conotação explora sentidos associados, figurados ou expressivos.",
                "DENOTAÇÃO = literal.\nCONOTAÇÃO = sentido associado/figurado.",
                "metáfora = aproximação implícita entre ideias\nconotação = valor adicional criado pelo contexto\npolissemia = uma palavra com vários sentidos relacionados",
                "'A porta está aberta' tende a ser literal. 'A educação abre portas' usa 'portas' conotativamente como oportunidades.",
                "Em textos publicitários, poéticos e humorísticos, uma palavra pode ativar simultaneamente o sentido literal e outro figurado.",
                "Contraexemplo: todo texto científico é totalmente sem conotação em qualquer trecho. O gênero tende à precisão, mas usos figurativos podem aparecer.",
                "Erro comum: chamar qualquer frase incomum de metáfora sem explicar a relação de sentido.",
                new String[]{"p_info_explicita","p_inferencia"},
                q("Em 'A notícia caiu como uma bomba na equipe', 'bomba' é usada principalmente em sentido:",1,
                        "literal, como explosivo real","O contexto fala do impacto da notícia, não de explosão física.",null,
                        "conotativo, para indicar forte impacto","Correto.",null,
                        "gramaticalmente plural","Número não é a questão.","p_numero",
                        "sem qualquer sentido","Há sentido figurado claro.",null),
                q("Qual opção apresenta uso mais denotativo de 'raiz'?",3,
                        "Precisamos atacar a raiz do problema.","'raiz' significa causa/origem em sentido figurado.",null,
                        "Ela nunca esqueceu suas raízes culturais.","Uso figurado ligado a origem/identidade.",null,
                        "A raiz da equação é 3.","É sentido técnico matemático, não o sentido físico botânico original; é convencional na matemática.","m_equacao1",
                        "A raiz da planta absorve água e sais minerais.","Correto: sentido botânico literal.",null)));

        add(m, n("p_generos","Português","Gêneros textuais e finalidade",2,
                "Gênero textual é uma forma social de comunicação com finalidade, público, contexto e organização recorrentes: notícia, anúncio, tirinha, artigo de opinião, receita, relatório etc.",
                "Para reconhecer gênero: quem fala? para quem? para quê? onde circula?",
                "finalidade = objetivo comunicativo\nsuporte = meio de circulação\npúblico-alvo = destinatários previstos\nestrutura composicional = organização recorrente",
                "Uma notícia tende a informar acontecimentos de interesse público; um artigo de opinião organiza defesa de ponto de vista; uma propaganda procura persuadir.",
                "O mesmo assunto pode aparecer em gêneros diferentes. 'Vacinação' numa notícia, numa campanha publicitária ou num artigo científico produzirá escolhas distintas de linguagem e estrutura.",
                "Contraexemplo: gênero é definido apenas pelo tamanho do texto.",
                "Erro comum: confundir assunto com gênero. 'Meio ambiente' é tema, não gênero.",
                new String[]{"p_info_explicita","p_tese_argumento"},
                q("Um texto apresenta título, data, descrição objetiva de um acontecimento recente e declarações de envolvidos. Qual gênero é mais provável?",0,
                        "notícia","Correto: os traços combinam com finalidade informativa jornalística.",null,
                        "receita culinária","Faltam ingredientes e instruções de preparo.",null,
                        "poema lírico","A organização descrita não aponta para esse gênero.",null,
                        "manual de instalação","Não há sequência de procedimentos técnicos.",null),
                q("Uma campanha usa imperativos, imagem de impacto e slogan para incentivar vacinação. A finalidade predominante é:",2,
                        "narrar ficção","Não há foco narrativo ficcional.",null,
                        "registrar experimento científico","Não é protocolo científico.",null,
                        "persuadir o público a adotar uma ação","Correto.",null,
                        "apenas descrever a gramática do slogan","Isso poderia ser objeto de análise, não finalidade do gênero.",null)));

        add(m, n("p_coesao","Português","Coesão e coerência",3,
                "Coesão são mecanismos que conectam partes do texto; coerência é a construção de um sentido global compatível entre informações, contexto e relações lógicas.",
                "COESÃO = liga partes.\nCOERÊNCIA = faz o conjunto ter sentido.",
                "coesão referencial = retomadas por pronomes, sinônimos, elipses\ncoesão sequencial = conectivos e progressão\ncoerência = compatibilidade lógica e contextual",
                "'Joana comprou um livro. Ela o leu em dois dias.' 'Ela' retoma Joana e 'o' retoma livro: coesão referencial. A sequência também é coerente.",
                "Um texto pode ter conectivos e ainda ser incoerente: 'Choveu muito, portanto o triângulo tem quatro lados'. A ligação gramatical existe, mas a relação lógica é absurda.",
                "Contraexemplo: coesão e coerência são sinônimos perfeitos.",
                "Erro comum: avaliar apenas palavras de ligação e não o sentido global.",
                new String[]{"p_pronome","p_conectivos","p_inferencia"},
                q("Em 'O laboratório recebeu novos microscópios. Esses equipamentos serão usados nas aulas', 'esses equipamentos' realiza:",1,
                        "oposição","Não há contraste.",null,
                        "retomada referencial de 'microscópios'","Correto.",null,
                        "mudança de assunto sem conexão","Há conexão explícita.",null,
                        "concordância verbal apenas","A função principal cobrada é coesiva/referencial.","p_concordancia_verbal"),
                q("Qual sequência é gramaticalmente coesa, mas semanticamente incoerente?",3,
                        "Estava chovendo, por isso levei guarda-chuva.","Coesa e coerente.",null,
                        "O livro acabou; portanto comecei outro.","Pode ser coerente.",null,
                        "A prova foi adiada porque faltou energia.","Relação causal plausível.",null,
                        "O círculo é redondo; portanto terça-feira pesa oito metros.","Correto: há conectivo, mas as ideias não formam relação coerente.",null)));

        add(m, n("p_intertextualidade","Português","Intertextualidade, paráfrase e paródia",3,
                "Intertextualidade ocorre quando um texto dialoga com outro texto, obra, fala conhecida ou gênero. Paráfrase retoma ideia preservando sentido central; paródia recria com alteração crítica, humorística ou inesperada.",
                "INTERTEXTO = um texto conversa com outro.",
                "paráfrase = reformulação preservando ideia\nparódia = recriação transformadora\nalusão = referência indireta\ncitação = reprodução identificada de trecho",
                "Um anúncio que adapta um verso famoso para vender um produto cria intertextualidade. Para interpretar, o leitor pode precisar reconhecer a fonte e a mudança feita.",
                "Paráfrase não é copiar palavras; é reconstruir a mesma ideia. Paródia normalmente depende da diferença entre original conhecido e nova versão.",
                "Contraexemplo: dois textos sobre o mesmo assunto são necessariamente intertextuais. Pode haver apenas coincidência temática.",
                "Erro comum: reconhecer a referência e não explicar o efeito produzido pela transformação.",
                new String[]{"p_generos","p_inferencia"},
                q("Uma charge reescreve um provérbio conhecido para criticar uma situação política. Isso é exemplo de:",2,
                        "apenas concordância nominal","Há fenômeno textual mais amplo.","p_concordancia_nominal",
                        "informação explícita sem relação externa","A compreensão depende do diálogo com outro enunciado.","p_info_explicita",
                        "intertextualidade","Correto.",null,
                        "ausência de contexto","Há justamente contexto cultural compartilhado.",null),
                q("Qual diferença resume melhor paráfrase e paródia?",0,
                        "paráfrase preserva a ideia central; paródia transforma a referência para novo efeito","Correto.",null,
                        "paráfrase sempre copia palavra por palavra","Isso seria reprodução, não definição de paráfrase.",null,
                        "paródia nunca depende de texto anterior","Ela depende da referência para produzir efeito.",null,
                        "são exatamente a mesma coisa","Não são.",null)));

        // ================= MATEMÁTICA =================
        add(m, n("m_conjuntos","Matemática","Conjuntos, pertinência e operações",1,
                "Conjunto é uma coleção bem definida de elementos. Pertinência liga elemento a conjunto; inclusão compara conjuntos.",
                "x ∈ A = x pertence a A.\nA ⊂ B = todo elemento de A está em B.",
                "união A∪B = elementos de A ou B\ninterseção A∩B = elementos comuns\ndiferença A−B = elementos de A que não estão em B\nconjunto vazio = nenhum elemento",
                "Se A={1,2,3} e B={3,4}, então A∪B={1,2,3,4} e A∩B={3}. O elemento 3 pertence a A; o conjunto {3} está contido em A.",
                "Em problemas de pesquisa, diagramas de Venn evitam contar duas vezes pessoas que pertencem a dois grupos.",
                "Contraexemplo: escrever 3⊂A quando 3 é elemento. O símbolo adequado é 3∈A.",
                "Erro comum: somar quantidades dos grupos sem descontar interseção.",
                new String[]{"m_operacoes"},
                q("A={1,2,5} e B={2,3,5}. Qual é A∩B?",1,
                        "{1,2,3,5}","Isso é a união.",null,
                        "{2,5}","Correto: são os elementos comuns.",null,
                        "{1,3}","São elementos exclusivos de cada conjunto, não comuns.",null,
                        "{}","Há elementos em comum.",null),
                q("Em uma turma, 18 gostam de Física, 14 de Química e 6 de ambas. Quantos gostam de pelo menos uma?",3,
                        "32","Conta os 6 da interseção duas vezes.",null,
                        "26","Subtração incorreta.",null,
                        "38","Soma e acrescenta a interseção.",null,
                        "26","Correto seria 18+14−6=26.",null)));
        // Corrige o distrator duplicado acima.
        StudyCatalog.Node conj = m.get("m_conjuntos");
        conj.transfer.options[1] = "20";
        conj.transfer.feedback[1] = "Subtraiu 12 em vez de descontar apenas a interseção de 6.";

        add(m, n("m_divisibilidade","Matemática","Divisibilidade, múltiplos e números primos",1,
                "Um número a é divisível por b quando a÷b tem resto zero. Múltiplos resultam de multiplicar; divisores cabem exatamente.",
                "MÚLTIPLO: vem da tabuada.\nDIVISOR: divide sem resto.",
                "primo = inteiro positivo maior que 1 com exatamente dois divisores positivos\npar = divisível por 2\nregra do 3 = soma dos algarismos divisível por 3\nregra do 9 = soma dos algarismos divisível por 9",
                "378 é divisível por 3 porque 3+7+8=18 e 18 é divisível por 3. Também é divisível por 9 porque 18 é múltiplo de 9.",
                "O número 1 não é primo: ele tem apenas um divisor positivo. 2 é o único primo par.",
                "Contraexemplo: todo número ímpar é primo. 9 é ímpar e composto.",
                "Erro comum: confundir fator/divisor com múltiplo.",
                new String[]{"m_operacoes"},
                q("Qual número é primo?",2,
                        "1","1 não é primo.",null,
                        "21","21=3×7.",null,
                        "29","Correto: divisores positivos apenas 1 e 29.",null,
                        "39","39=3×13.",null),
                q("Sem efetuar divisão longa, por que 7 452 é divisível por 3?",1,
                        "Porque termina em 2","Isso testa divisibilidade por 2.",null,
                        "Porque 7+4+5+2=18, e 18 é divisível por 3","Correto.",null,
                        "Porque começa em 7","Não existe essa regra.",null,
                        "Porque tem quatro algarismos","Quantidade de algarismos não determina divisibilidade por 3.",null)));

        add(m, n("m_mdc_mmc","Matemática","MDC e MMC",1,
                "MDC é o maior divisor comum; MMC é o menor múltiplo comum positivo. Eles resolvem tipos diferentes de sincronização e repartição.",
                "MMC = quando eventos precisam coincidir.\nMDC = maior tamanho de grupos iguais sem sobra.",
                "fatoração prima = decompor em fatores primos\nMDC = fatores comuns com menores expoentes\nMMC = todos os fatores necessários com maiores expoentes",
                "12=2²·3 e 18=2·3². MDC=2·3=6. MMC=2²·3²=36.",
                "Dois sinais piscam a cada 12 s e 18 s. Voltam a coincidir após MMC(12,18)=36 s.",
                "Contraexemplo: usar MMC para dividir 24 e 36 objetos em grupos iguais do maior tamanho possível; ali o raciocínio é MDC.",
                "Erro comum: decorar método sem identificar se o problema pede encontro periódico ou divisão em grupos.",
                new String[]{"m_divisibilidade"},
                q("Dois ônibus passam por um ponto a cada 20 e 30 minutos. Se passaram juntos agora, em quanto tempo coincidem novamente?",2,
                        "10 min","É o MDC, não o primeiro múltiplo comum positivo.",null,
                        "50 min","Soma dos intervalos não resolve ciclos.",null,
                        "60 min","Correto: MMC(20,30)=60.",null,
                        "600 min","Produto sem simplificação; não é o menor múltiplo comum.",null),
                q("Há 48 lápis e 60 canetas para montar o maior número de kits idênticos sem sobra. Quantos kits?",0,
                        "12","Correto: MDC(48,60)=12 kits; cada um terá 4 lápis e 5 canetas.",null,
                        "108","Soma dos itens, não quantidade de kits.",null,
                        "240","MMC não é adequado para repartição máxima em grupos iguais.",null,
                        "5","É apenas a quantidade de canetas por kit quando há 12 kits.",null)));

        add(m, n("m_potencia","Matemática","Potenciação e propriedades",1,
                "Potência aⁿ representa multiplicação repetida da base a por ela mesma n vezes para expoente natural positivo.",
                "MESMA BASE: multiplicar → soma expoentes; dividir → subtrai expoentes.",
                "base = número que se repete\nexpoente = quantidade/estrutura da repetição\na⁰=1 para a≠0\na⁻ⁿ=1/aⁿ",
                "2³·2⁴=2⁷ porque são 3+4 fatores 2. Já 2³+2⁴ não vira 2⁷: propriedade vale para multiplicação, não soma.",
                "(3²)⁴=3⁸ porque potência de potência multiplica expoentes.",
                "Contraexemplo: (a+b)²=a²+b². O termo 2ab não pode ser ignorado.",
                "Erro comum: aplicar propriedades de produto em adição.",
                new String[]{"m_operacoes"},
                q("Quanto vale 5³·5²?",0,
                        "5⁵","Correto: mesma base em multiplicação → 3+2.",null,
                        "25⁵","Multiplicou bases e somou expoentes ao mesmo tempo.",null,
                        "5⁶","Multiplicou expoentes indevidamente.",null,
                        "10⁵","Somou bases, o que não é propriedade de potência.",null),
                q("Simplifique (2³)⁴ / 2⁵.",3,
                        "2²","Potência de potência foi tratada incorretamente.",null,
                        "2⁶","Os expoentes não foram combinados corretamente.",null,
                        "2²⁰","Multiplicou tudo sem usar as propriedades.",null,
                        "2⁷","Correto: (2³)⁴=2¹²; 2¹²/2⁵=2⁷.",null)));

        add(m, n("m_radiciacao","Matemática","Radiciação e raízes",1,
                "Raiz é operação relacionada à potência. √a é o número não negativo cujo quadrado vale a, no conjunto real quando a≥0.",
                "√49=7 porque 7²=49.",
                "radicando = número dentro da raiz\níndice = grau da raiz\nraiz quadrada principal = valor não negativo",
                "√72=√(36·2)=6√2. Separar fatores quadrados perfeitos simplifica a expressão.",
                "x²=25 tem duas soluções x=±5, embora √25 seja definido como 5 na raiz principal.",
                "Contraexemplo: √(a+b)=√a+√b em geral. Ex.: √9=3, mas √4+√5≠3.",
                "Erro comum: confundir raiz principal com soluções de uma equação quadrática.",
                new String[]{"m_potencia","m_fatoracao"},
                q("Simplifique √50.",1,
                        "25√2","Extraiu 25 em vez de sua raiz 5.",null,
                        "5√2","Correto: 50=25·2.",null,
                        "10√5","Esse quadrado não reconstrói 50.",null,
                        "√25+√2","Raiz de produto pode separar nesse caso; raiz de soma não é a mesma coisa.",null),
                q("Se x²=81, quais soluções reais?",2,
                        "x=9 apenas","Perde a solução negativa.",null,
                        "x=−9 apenas","Perde a solução positiva.",null,
                        "x=−9 ou x=9","Correto.",null,
                        "x=√81=81","√81=9, não 81.",null)));

        add(m, n("m_notacao","Matemática","Notação científica e ordem de grandeza",2,
                "Notação científica escreve números como a×10ⁿ, com 1≤|a|<10. Facilita comparação e cálculo com valores muito grandes ou pequenos.",
                "Mova a vírgula até sobrar um número entre 1 e 10; conte as casas no expoente.",
                "expoente positivo = número grande\nexpoente negativo = número menor que 1\nordem de grandeza = potência de 10 usada para estimar escala",
                "3 200 000 = 3,2×10⁶. 0,00045 = 4,5×10⁻⁴.",
                "(2×10³)(4×10⁵)=8×10⁸. Coeficientes multiplicam; potências de 10 somam expoentes.",
                "Contraexemplo: 32×10⁵ como forma científica padrão; o coeficiente deveria ficar abaixo de 10.",
                "Erro comum: inverter o sinal do expoente ao deslocar a vírgula.",
                new String[]{"m_potencia","m_decimal"},
                q("0,000072 em notação científica é:",2,
                        "7,2×10⁵","Expoente positivo produziria número grande.",null,
                        "72×10⁻⁶","Tem valor equivalente, mas não está normalizado com coeficiente entre 1 e 10.",null,
                        "7,2×10⁻⁵","Correto.",null,
                        "0,72×10⁻⁴","Equivalente, mas coeficiente não está na forma padrão.",null),
                q("Quanto vale (3×10⁴)(2×10⁻³) em forma científica?",0,
                        "6×10¹","Correto: 3·2=6 e 10⁴·10⁻³=10¹.",null,
                        "5×10¹","Coeficientes devem multiplicar, não somar.",null,
                        "6×10⁻¹²","Multiplicou expoentes em vez de somá-los.",null,
                        "6×10⁷","Somou 4 e 3 sem considerar o sinal negativo.",null)));

        add(m, n("m_regra3_inversa","Matemática","Grandezas inversamente proporcionais",2,
                "Grandezas inversamente proporcionais mudam em sentidos opostos mantendo produto constante no modelo: se uma dobra, a outra cai pela metade.",
                "DIRETA: dobro → dobro.\nINVERSA: dobro → metade.",
                "produto constante = x·y=k\nproporção inversa = y=k/x\ncondição do modelo = demais fatores permanecem equivalentes",
                "5 trabalhadores fazem serviço em 12 dias. Com produtividade igual e trabalho fixo, 10 trabalhadores → 6 dias, pois 5·12=10·6.",
                "Velocidade e tempo para distância fixa também são inversos: dobrar a velocidade reduz o tempo pela metade.",
                "Contraexemplo: mais trabalhadores sempre reduzem tempo exatamente de forma inversa na vida real; coordenação e limites podem quebrar o modelo.",
                "Erro comum: montar regra de três direta só porque os números aparecem em duas colunas.",
                new String[]{"m_razao"},
                q("Uma obra leva 18 dias com 4 equipes iguais. No modelo inverso, com 6 equipes levaria:",1,
                        "27 dias","Trata como proporcionalidade direta.",null,
                        "12 dias","Correto: 4·18=6·12.",null,
                        "16 dias","Não mantém o produto constante.",null,
                        "3 dias","Redução exagerada.",null),
                q("Para percorrer distância fixa, um veículo leva 5 h a 60 km/h. A 75 km/h, quanto tempo no mesmo modelo?",3,
                        "6,25 h","Aumentou tempo junto com velocidade, como relação direta.",null,
                        "5 h","Ignora mudança de velocidade.",null,
                        "3 h","Não mantém distância constante.",null,
                        "4 h","Correto: 60·5=75·t → t=4.",null)));

        add(m, n("m_juros","Matemática","Juros simples e compostos",3,
                "Juro é remuneração/custo do capital ao longo do tempo. No simples, juros crescem sobre o capital inicial; no composto, cada período incide sobre o saldo acumulado.",
                "SIMPLES: J=C·i·t.\nCOMPOSTO: M=C(1+i)^t.",
                "capital C = valor inicial\ntaxa i = percentual por período\nmontante M = capital + juros\nperíodo = unidade de tempo compatível com a taxa",
                "R$1 000 a 2% ao mês por 3 meses: simples J=1000·0,02·3=60 → M=1060. Composto M=1000·1,02³≈1061,21.",
                "Diferença cresce com tempo/taxa porque no composto há 'juros sobre juros'.",
                "Contraexemplo: usar taxa mensal com tempo em anos sem converter unidades.",
                "Erro comum: usar 2 em vez de 0,02 para 2%.",
                new String[]{"m_porcentagem","m_potencia"},
                q("R$500 a juros simples de 3% ao mês por 4 meses gera quanto de juros?",2,
                        "R$15","Esse é juro de apenas um mês.",null,
                        "R$45","Corresponde a três meses.",null,
                        "R$60","Correto: 500·0,03·4=60.",null,
                        "R$560","Esse é o montante, não o valor dos juros.",null),
                q("R$1 000 a 10% ao período por 2 períodos, juros compostos. Montante?",1,
                        "R$1 200","Isso é juros simples de 10% em dois períodos.",null,
                        "R$1 210","Correto: 1000·1,1²=1210.",null,
                        "R$1 100","Apenas um período.",null,
                        "R$2 000","Não corresponde ao crescimento percentual dado.",null)));

        add(m, n("m_polinomios","Matemática","Monômios, polinômios e operações",2,
                "Polinômio é soma de termos algébricos com expoentes inteiros não negativos. Somar polinômios exige juntar termos semelhantes; multiplicar usa distributiva.",
                "Só some termos com mesma parte literal e expoentes.",
                "monômio = um termo\ngrau = maior expoente relevante\ncoeficiente = número do termo\ntermos semelhantes = mesma parte literal",
                "(2x²+3x−1)+(x²−5x+4)=3x²−2x+3. Cada tipo de termo é agrupado separadamente.",
                "x(x+3)=x²+3x pela distributiva.",
                "Contraexemplo: x²+x=2x². Os termos não são semelhantes.",
                "Erro comum: multiplicar expoentes quando deveria somá-los em produto de mesma base.",
                new String[]{"m_algebra","m_distributiva","m_potencia"},
                q("Simplifique 3x²+2x−5 + 4x²−7x+1.",0,
                        "7x²−5x−4","Correto.",null,
                        "7x⁴−5x−4","Somar termos x² não aumenta expoente.","m_potencia",
                        "12x²−5x−4","Multiplicou coeficientes em vez de somar.",null,
                        "7x²+9x−6","Sinais foram combinados incorretamente.","m_inteiros"),
                q("Quanto vale (x+2)(x−3)?",2,
                        "x²−6","Faltam termos cruzados.",null,
                        "x²−x+6","O produto 2·(−3) é −6.","m_inteiros",
                        "x²−x−6","Correto: x²−3x+2x−6.",null,
                        "x²+5x−6","Termos cruzados somam −x, não +5x.",null)));

        add(m, n("m_angulos","Matemática","Ângulos e relações em retas",2,
                "Ângulo mede abertura entre semirretas. Ângulos complementares somam 90°, suplementares somam 180°; opostos pelo vértice são iguais.",
                "COMPLEMENTARES=90°.\nSUPLEMENTARES=180°.\nOPV=iguais.",
                "ângulo reto =90°\nraso=180°\nagudo<90°\nobtuso entre 90° e 180°",
                "Se dois ângulos adjacentes formam uma linha reta e um mede 127°, o outro mede 53°.",
                "Em duas retas que se cruzam, se um ângulo é 70°, seu oposto pelo vértice também é 70°.",
                "Contraexemplo: ângulos adjacentes são sempre iguais. Só relações específicas garantem igualdade.",
                "Erro comum: confundir complemento com suplemento.",
                new String[]{"m_operacoes"},
                q("O suplemento de 38° é:",1,
                        "52°","Esse é o complemento.",null,
                        "142°","Correto: 180−38=142.",null,
                        "218°","Somou em vez de completar 180.",null,
                        "38°","Só seria igual em caso específico de 90° para OPV etc.",null),
                q("Duas retas se cruzam. Um dos ângulos mede 112°. O ângulo oposto pelo vértice mede:",2,
                        "68°","68° é suplemento do adjacente.",null,
                        "248°","Não é ângulo interno simples do cruzamento.",null,
                        "112°","Correto.",null,
                        "56°","Não há regra de metade.",null)));

        add(m, n("m_semelhanca","Matemática","Semelhança de triângulos",2,
                "Triângulos semelhantes têm ângulos correspondentes iguais e lados correspondentes proporcionais. A forma é a mesma, a escala pode mudar.",
                "SEMELHANTE = mesmos ângulos + lados na mesma razão.",
                "razão de semelhança = fator entre lados correspondentes\ncorrespondência = pares de vértices/lados equivalentes\ncongruente = mesma forma e mesmo tamanho",
                "Se um triângulo 3-4-5 é ampliado por fator 2, obtém-se 6-8-10. Os ângulos permanecem iguais.",
                "Se razão linear é 3, áreas crescem por 3²=9.",
                "Contraexemplo: lados proporcionais em ordem errada. É preciso respeitar correspondência.",
                "Erro comum: comparar o maior lado de um triângulo com o menor do outro.",
                new String[]{"m_razao","m_angulos"},
                q("Triângulos semelhantes têm lados correspondentes 4 e 10. Se outro lado do menor mede 6, o correspondente do maior mede:",2,
                        "12","Usa fator 2, não 2,5.",null,
                        "14","Soma 8 em vez de usar razão.",null,
                        "15","Correto: fator 10/4=2,5; 6×2,5=15.",null,
                        "24","Multiplica por 4.",null),
                q("Duas figuras semelhantes têm razão linear 1:4. Qual razão entre suas áreas?",0,
                        "1:16","Correto: áreas variam com quadrado da escala linear.",null,
                        "1:4","Isso vale para comprimentos.",null,
                        "1:8","Não corresponde ao quadrado do fator.",null,
                        "1:64","Seria cubo, relacionado a volumes de sólidos semelhantes.",null)));

        add(m, n("m_tales","Matemática","Teorema de Tales",2,
                "Retas paralelas cortadas por transversais determinam segmentos proporcionais. O Teorema de Tales transforma geometria em proporção.",
                "PARALELAS + TRANSVERSAIS → segmentos proporcionais.",
                "transversal = reta que corta outras\nsegmentos correspondentes = partes associadas na mesma posição\nproporção = igualdade de razões",
                "Se três paralelas cortam duas transversais gerando segmentos 2 e 3 numa transversal e 4 e x na outra, 2/3=4/x → 2x=12 → x=6.",
                "O teorema também fundamenta várias construções de semelhança de triângulos.",
                "Contraexemplo: aplicar a proporção quando as retas indicadas não são paralelas.",
                "Erro comum: cruzar segmentos que não correspondem.",
                new String[]{"m_razao","m_equacao1","m_semelhanca"},
                q("Segmentos correspondentes medem 3 e 5 numa transversal, 6 e x na outra. Qual x?",1,
                        "8","Não preserva razão 3/5=6/x.",null,
                        "10","Correto: 3/5=6/x → 3x=30 → x=10.",null,
                        "12","Fator deveria ser 2: 3→6, então 5→10.",null,
                        "15","Multiplica 3×5 sem usar correspondência.",null),
                q("Qual condição é essencial para aplicar a forma clássica do Teorema de Tales?",3,
                        "todos os ângulos serem retos","Não é necessário.",null,
                        "todos os segmentos terem mesmo comprimento","Não.",null,
                        "existir um círculo","Não faz parte da hipótese.",null,
                        "um feixe de retas paralelas cortado por transversais","Correto.",null)));

        add(m, n("m_areas","Matemática","Perímetro e áreas planas",2,
                "Perímetro mede contorno; área mede superfície. As unidades revelam a diferença: comprimento usa unidades lineares; área usa unidades quadradas.",
                "PERÍMETRO = borda.\nÁREA = superfície.",
                "retângulo A=b·h\ntriângulo A=b·h/2\nparalelogramo A=b·h\ntrapézio A=(B+b)h/2",
                "Retângulo 8 m por 5 m: perímetro=2(8+5)=26 m; área=8·5=40 m².",
                "Triângulo com base 10 cm e altura 6 cm: área=10·6/2=30 cm². A altura deve ser perpendicular à base escolhida.",
                "Contraexemplo: somar lados para obter área.",
                "Erro comum: esquecer unidade ao quadrado ou usar lado inclinado como altura sem perpendicularidade.",
                new String[]{"m_operacoes","m_decimal"},
                q("Um terreno retangular mede 12 m por 7 m. Sua área é:",2,
                        "38 m","Isso é perímetro e ainda deveria usar unidade linear.",null,
                        "19 m²","É soma das dimensões.",null,
                        "84 m²","Correto.",null,
                        "168 m²","Dobrou a área sem motivo.",null),
                q("Um triângulo tem área 48 cm² e base 12 cm. Qual altura relativa a essa base?",1,
                        "4 cm","Se h=4, área seria 24.",null,
                        "8 cm","Correto: 48=12·h/2 → 96=12h → h=8.",null,
                        "12 cm","Área seria 72.",null,
                        "96 cm","Confunde dobro da área com altura.",null)));

        add(m, n("m_circulo","Matemática","Circunferência e círculo",2,
                "Circunferência é a linha cujos pontos estão à mesma distância do centro; círculo inclui a região interna. Comprimento C=2πr; área A=πr².",
                "CONTORNO: 2πr.\nÁREA: πr².",
                "raio r = centro até borda\ndiâmetro d=2r\nπ≈3,14 em aproximações comuns",
                "Raio 3 cm: comprimento=6π cm; área=9π cm².",
                "Se o raio dobra, comprimento dobra, mas área quadruplica porque depende de r².",
                "Contraexemplo: usar πr² para comprimento.",
                "Erro comum: receber diâmetro e tratá-lo como raio.",
                new String[]{"m_potencia","m_areas"},
                q("Círculo de diâmetro 10 cm. Qual área?",0,
                        "25π cm²","Correto: r=5; A=π·25.",null,
                        "100π cm²","Usou diâmetro como raio.",null,
                        "10π cm²","Não corresponde à fórmula de área.",null,
                        "20π cm²","É relacionado ao comprimento se r=10, mas não ao caso dado.",null),
                q("Se o raio de um círculo triplica, sua área é multiplicada por:",2,
                        "3","Isso vale para comprimento.",null,
                        "6","Não.",null,
                        "9","Correto: (3r)²=9r².",null,
                        "27","Isso seria cubo, não área.",null)));

        add(m, n("m_trig","Matemática","Razões trigonométricas no triângulo retângulo",3,
                "Seno, cosseno e tangente relacionam lados e ângulos de triângulos retângulos.",
                "sen=oposto/hipotenusa.\ncos=adjacente/hipotenusa.\ntan=oposto/adjacente.",
                "cateto oposto = frente ao ângulo\ncateto adjacente = junto ao ângulo, exceto hipotenusa\nhipotenusa = oposto ao ângulo de 90°",
                "Num triângulo 3-4-5, para o ângulo cujo lado oposto vale 3: sen=3/5, cos=4/5, tan=3/4.",
                "A classificação de oposto/adjacente depende do ângulo escolhido; a hipotenusa não muda.",
                "Contraexemplo: chamar sempre o lado 3 de oposto sem informar o ângulo.",
                "Erro comum: colocar hipotenusa no denominador da tangente.",
                new String[]{"m_pitagoras","m_fracao"},
                q("Num triângulo retângulo, em relação ao ângulo θ, cateto oposto=6 e hipotenusa=10. sen θ =",1,
                        "10/6","Inverte a razão.",null,
                        "3/5","Correto: 6/10 simplifica para 3/5.",null,
                        "4/5","Esse poderia ser cosseno se o adjacente fosse 8.",null,
                        "6/8","Isso seria tangente se adjacente=8.",null),
                q("Num triângulo 5-12-13, para o ângulo oposto ao cateto 5, qual é tan θ?",3,
                        "5/13","Isso é seno.",null,
                        "12/13","Isso é cosseno.",null,
                        "13/12","Inclui hipotenusa indevidamente.",null,
                        "5/12","Correto.",null)));

        // ================= FÍSICA =================
        add(m, n("f_aceleracao","Física","Aceleração",2,
                "Aceleração mede quanto a velocidade varia por unidade de tempo: a=Δv/Δt. Pode existir por mudança de módulo ou direção da velocidade.",
                "ACELERAÇÃO = mudança da velocidade / tempo.",
                "m/s² = unidade SI\naceleração positiva/negativa depende do eixo escolhido\nmovimento curvo pode ter aceleração mesmo com rapidez constante",
                "Velocidade passa de 5 para 17 m/s em 4 s: a=(17−5)/4=3 m/s².",
                "Frear de 20 para 8 m/s em 3 s: a=(8−20)/3=−4 m/s² no eixo positivo do movimento.",
                "Contraexemplo: aceleração negativa sempre significa aumentar rapidez para trás; sinal depende do referencial e da velocidade.",
                "Erro comum: usar velocidade final/tempo sem subtrair a inicial.",
                new String[]{"f_velocidade","m_inteiros"},
                q("Velocidade muda de 10 m/s para 22 m/s em 6 s. Aceleração média?",2,
                        "5,3 m/s²","Divisão incorreta.",null,
                        "12 m/s²","Usou apenas variação de velocidade sem dividir pelo tempo.",null,
                        "2 m/s²","Correto: 12/6=2.",null,
                        "32 m/s²","Somou velocidades.",null),
                q("Um carro faz curva com rapidez constante. Pode haver aceleração?",0,
                        "Sim, porque a direção da velocidade muda","Correto.",null,
                        "Não, aceleração só existe quando o velocímetro muda","Velocidade é vetor; direção também importa.",null,
                        "Só se a massa mudar","Massa não é condição para aceleração cinemática.",null,
                        "Só se parar completamente","Não.",null)));

        add(m, n("f_massa_peso","Física","Massa, peso e gravidade",2,
                "Massa mede inércia e é expressa em kg; peso é força gravitacional P=m·g e é expresso em newtons.",
                "MASSA em kg.\nPESO em N.",
                "g = aceleração gravitacional\npeso = força\nmassa = propriedade do corpo no modelo clássico",
                "Pessoa de 60 kg, usando g≈10 m/s²: peso≈600 N na Terra. Na Lua a massa permanece 60 kg, mas o peso é menor por g menor.",
                "Balanças comuns são calibradas para indicar massa a partir de efeitos relacionados à força normal/peso no ambiente terrestre.",
                "Contraexemplo: dizer 'peso 60 kg' em linguagem física rigorosa; 60 kg é massa.",
                "Erro comum: trocar unidade ou achar que massa muda ao mudar de planeta.",
                new String[]{"f_newton","f_unidades"},
                q("Corpo de massa 8 kg em local com g=10 m/s². Peso?",1,
                        "0,8 N","Dividiu em vez de multiplicar.",null,
                        "80 N","Correto.",null,
                        "8 N","Confunde valor numérico de massa e peso.",null,
                        "800 kg","Unidade e cálculo incorretos.",null),
                q("Astronauta vai da Terra à Lua. Qual grandeza permanece essencialmente a mesma no modelo escolar?",2,
                        "peso","Peso muda com g.",null,
                        "força gravitacional","Também muda.",null,
                        "massa","Correto.",null,
                        "aceleração da gravidade","É menor na Lua.",null)));

        add(m, n("f_energia","Física","Trabalho, potência e energia",3,
                "Trabalho é transferência de energia por força ao longo de deslocamento; potência mede rapidez dessa transferência. Energia cinética depende do movimento; potencial pode depender da posição.",
                "Ec=mv²/2.\nEp=mgh.\nPotência=energia/tempo.",
                "joule J = energia/trabalho\nwatt W = joule por segundo\nconservação de energia = energia transforma-se; total de sistema isolado permanece",
                "Corpo 2 kg a 3 m/s: Ec=2·9/2=9 J. Se velocidade dobra, Ec quadruplica por causa de v².",
                "Máquinas que realizam o mesmo trabalho em tempos diferentes têm potências diferentes: menor tempo → maior potência.",
                "Contraexemplo: potência é quantidade total de energia. Ela mede taxa de uso/transferência.",
                "Erro comum: esquecer o quadrado da velocidade na energia cinética.",
                new String[]{"f_newton","m_potencia"},
                q("Se a velocidade de um corpo dobra, mantendo massa, sua energia cinética:",3,
                        "dobra","Ec depende de v².",null,
                        "não muda","Muda com velocidade.",null,
                        "fica pela metade","Não.",null,
                        "quadruplica","Correto.",null),
                q("Duas máquinas fazem 600 J de trabalho; A leva 3 s e B leva 6 s. Potências?",0,
                        "A=200 W e B=100 W","Correto.",null,
                        "A=1800 W e B=3600 W","Multiplicou energia por tempo.",null,
                        "ambas 600 W","Ignora tempo.",null,
                        "A=2 W e B=1 W","Razão incorreta.",null)));

        add(m, n("f_ondas","Física","Ondas, som e luz",3,
                "Onda transporta energia/informação sem transportar matéria de forma líquida junto com a perturbação em todo o percurso. Frequência, comprimento de onda e velocidade relacionam-se por v=λf.",
                "v = λ·f.\nSom precisa de meio material; luz pode se propagar no vácuo.",
                "frequência Hz = oscilações por segundo\ncomprimento λ = distância entre pontos equivalentes\namplitude = relacionada à intensidade em vários contextos",
                "Onda de velocidade 20 m/s e frequência 5 Hz: λ=20/5=4 m.",
                "Som não atravessa vácuo porque é onda mecânica; luz é eletromagnética e atravessa o vácuo.",
                "Contraexemplo: frequência maior sempre significa onda mais rápida no mesmo meio. Se v é fixa, frequência maior implica λ menor.",
                "Erro comum: confundir frequência (altura do som) com amplitude (intensidade sonora em modelo simples).",
                new String[]{"f_unidades","m_razao"},
                q("Onda tem λ=2 m e f=6 Hz. Velocidade?",1,
                        "3 m/s","Dividiu em vez de multiplicar.",null,
                        "12 m/s","Correto.",null,
                        "8 m/s","Somou grandezas.",null,
                        "36 m/s","Elevou/multiplicou indevidamente.",null),
                q("No mesmo meio, velocidade de onda é constante. Se frequência dobra, comprimento de onda:",2,
                        "dobra","Isso faria v quadruplicar.",null,
                        "não muda","Então v dobraria.",null,
                        "cai pela metade","Correto: λ=v/f.",null,
                        "fica zero","Não.",null)));

        add(m, n("f_ohm","Física","Circuitos elétricos e Lei de Ohm",3,
                "Tensão, corrente e resistência relacionam-se por U=R·I em resistor ôhmico. Potência elétrica pode ser P=U·I.",
                "U=R·I.\nP=U·I.",
                "tensão U = volt V\ncorrente I = ampère A\nresistência R = ohm Ω\npotência P = watt W",
                "Resistor 6 Ω sob 12 V: I=12/6=2 A. Potência=12·2=24 W.",
                "A resistência expressa oposição à corrente no modelo; aumentar R com mesma U reduz I.",
                "Contraexemplo: corrente é 'gasta' completamente pelo primeiro componente. Em circuitos, cargas circulam e energia é transferida; análise depende da associação.",
                "Erro comum: multiplicar U·R para achar corrente.",
                new String[]{"m_equacao1","f_unidades"},
                q("Resistor 10 Ω ligado a 20 V. Corrente?",2,
                        "200 A","Multiplicou U·R.",null,
                        "0,5 A","Inverteu razão.",null,
                        "2 A","Correto.",null,
                        "30 A","Somou valores de grandezas diferentes.",null),
                q("Um aparelho opera em 120 V e corrente 5 A. Potência elétrica?",0,
                        "600 W","Correto: P=UI.",null,
                        "24 W","Dividiu tensão por corrente.",null,
                        "125 W","Somou valores.",null,
                        "0,0417 W","Inverteu a razão.",null)));

        // ================= QUÍMICA =================
        add(m, n("q_periodica","Química","Tabela periódica, famílias e períodos",2,
                "Tabela periódica organiza elementos por número atômico crescente e propriedades periódicas. Colunas são grupos/famílias; linhas são períodos.",
                "GRUPO = coluna.\nPERÍODO = linha.\nZ cresce ao longo da tabela.",
                "metais = maioria à esquerda/centro\nnão metais = região direita, além do H\ngases nobres = grupo 18\nmetais alcalinos = grupo 1, exceto H",
                "Elementos do mesmo grupo tendem a compartilhar características químicas por configurações de elétrons de valência semelhantes no modelo escolar.",
                "O número atômico define a identidade; posição ajuda a prever propriedades, não muda Z.",
                "Contraexemplo: período é coluna vertical.",
                "Erro comum: confundir número de massa com posição ordenadora da tabela.",
                new String[]{"q_numero_atomico"},
                q("Na tabela periódica, elementos do mesmo grupo estão:",0,
                        "na mesma coluna","Correto.",null,
                        "na mesma linha","Isso é período.",null,
                        "com o mesmo número de massa","Não é requisito.",null,
                        "sempre no mesmo estado físico","Não.",null),
                q("Por que o número atômico é central na organização moderna da tabela?",1,
                        "Porque mede apenas nêutrons","Z é prótons.","q_numero_atomico",
                        "Porque identifica o elemento pelo número de prótons","Correto.",null,
                        "Porque é sempre igual ao número de massa","Nem sempre.","q_numero_atomico",
                        "Porque depende da temperatura","Não.",null)));

        add(m, n("q_ligacoes","Química","Ligações químicas",3,
                "Ligações químicas descrevem interações que mantêm átomos unidos. No modelo básico: iônica envolve atração entre íons; covalente envolve compartilhamento de pares eletrônicos; metálica descreve ligação em metais.",
                "IÔNICA = íons.\nCOVALENTE = compartilhamento.\nMETÁLICA = rede metálica.",
                "cátion = íon positivo\nânion = íon negativo\nelétrons de valência = elétrons mais envolvidos nas ligações",
                "NaCl é modelado como rede iônica de Na⁺ e Cl⁻. H₂O possui ligações covalentes entre H e O.",
                "A classificação de ligação é modelo; propriedades macroscópicas dependem da estrutura completa, não só de uma palavra.",
                "Contraexemplo: molécula de NaCl isolada como descrição completa de cristal iônico macroscópico; o sólido forma rede.",
                "Erro comum: achar que ligação iônica é compartilhamento igual de elétrons.",
                new String[]{"q_atomo","q_periodica"},
                q("Qual descrição combina melhor com ligação covalente?",2,
                        "atração entre núcleos sem elétrons","Elétrons são essenciais.",null,
                        "transferência e atração de íons apenas","Isso caracteriza o modelo iônico.",null,
                        "compartilhamento de pares de elétrons entre átomos","Correto.",null,
                        "ausência de interação entre átomos","Contradiz ligação.",null),
                q("Quando um átomo perde elétrons e fica com mais prótons que elétrons, forma:",0,
                        "cátion","Correto: carga positiva.",null,
                        "ânion","Ânion é negativo.","q_atomo",
                        "nêutron","Partícula nuclear, não espécie iônica.","q_atomo",
                        "isótopo necessariamente","Perda de elétron não altera nêutrons/protons.","q_numero_atomico")));

        add(m, n("q_ph","Química","Ácidos, bases e pH",3,
                "Em abordagem escolar, pH é escala relacionada à acidez/basicidade de soluções aquosas. pH menor que 7 é ácido; maior que 7 é básico; 7 é neutro em condições usuais de referência.",
                "pH<7 ácido.\npH=7 neutro.\npH>7 básico.",
                "ácido/base = conceitos que podem ser definidos por diferentes teorias\nindicador = substância que muda propriedade/cor conforme meio\nneutralização = reação ácido-base em modelos escolares",
                "Solução pH 3 é ácida; pH 11 é básica. A escala é logarítmica em tratamento mais avançado, então diferença de 1 unidade não representa diferença linear simples.",
                "Indicadores ajudam a estimar faixa de pH, mas não transformam uma solução em ácido/base por causa da cor.",
                "Contraexemplo: pH 2 é 'um pouco' mais ácido que pH 3 numa relação linear; a escala envolve potências de dez.",
                "Erro comum: inverter ácido e básico.",
                new String[]{"q_materia","m_potencia"},
                q("Uma solução com pH 10 é classificada, no modelo básico, como:",1,
                        "ácida","Ácidos têm pH abaixo de 7 nessa referência.",null,
                        "básica","Correto.",null,
                        "neutra","Neutra seria próxima de 7.",null,
                        "necessariamente sal puro","pH não determina isso.",null),
                q("Comparando pH 3 e pH 4, qual afirmação é mais adequada?",3,
                        "São idênticos porque ambos são ácidos","A acidez não é idêntica.",null,
                        "pH 4 é mais ácido","Quanto menor pH, maior acidez na escala usual.",null,
                        "a diferença é meramente estética","Não.",null,
                        "pH 3 corresponde a concentração de H⁺ aproximadamente dez vezes maior que pH 4 em tratamento idealizado","Correto.",null)));

        add(m, n("q_reacoes","Química","Reações, equações e conservação",3,
                "Equação química representa reagentes transformando-se em produtos. Coeficientes são ajustados para conservar quantidade de átomos de cada elemento.",
                "Balancear = mesmo número de cada átomo antes e depois.",
                "coeficiente = número antes da fórmula\níndice = número dentro da fórmula e parte da identidade da substância\nbalanceamento = alterar coeficientes, não índices",
                "H₂ + O₂ → H₂O não está balanceada em oxigênio. 2H₂ + O₂ → 2H₂O conserva 4 H e 2 O em cada lado.",
                "Mudar H₂O para H₂O₂ não é balancear: cria outra substância.",
                "Contraexemplo: editar índices das fórmulas para igualar contagens.",
                "Erro comum: esquecer que coeficiente multiplica todos os átomos da fórmula.",
                new String[]{"q_transformacao","q_atomo"},
                q("Qual equação está balanceada?",1,
                        "H₂ + O₂ → H₂O","Há 2 O à esquerda e 1 à direita.",null,
                        "2H₂ + O₂ → 2H₂O","Correto.",null,
                        "H₂ + 2O₂ → H₂O","Oxigênio fica ainda mais desequilibrado.",null,
                        "H₄ + O₂ → 2H₂O","H₄ não representa simplesmente ajustar coeficiente do H₂; muda a fórmula escrita.",null),
                q("Por que não devemos alterar índices para balancear uma equação?",2,
                        "Porque índices não têm significado","Têm significado na fórmula.",null,
                        "Porque coeficientes são sempre iguais a 1","Não.",null,
                        "Porque mudar o índice muda a composição/identidade da substância representada","Correto.",null,
                        "Porque átomos podem desaparecer","Conservação justamente impede desaparecimento no modelo.",null)));

        // ================= BIOLOGIA =================
        add(m, n("b_organelas","Biologia","Organelas e funções celulares",2,
                "Organelas são estruturas especializadas em células eucariontes. Entender função é mais útil que decorar lista.",
                "MITOCÔNDRIA = respiração celular/ATP.\nRIBOSSOMO = proteína.\nCLOROPLASTO = fotossíntese em vegetais/algas.",
                "lisossomo = digestão intracelular em abordagem escolar\nretículo endoplasmático = síntese/transporte\ncomplexo golgiense = modifica/empacota/secreta\nmitocôndria = etapas da respiração aeróbia",
                "Célula muscular ativa possui muitas mitocôndrias por alta demanda energética. Células secretoras têm complexo de Golgi/retículo desenvolvidos.",
                "Ribossomos existem também em procariontes; não são organelas membranosas.",
                "Contraexemplo: mitocôndria 'produz energia do nada'. Ela transforma energia química por processos metabólicos.",
                "Erro comum: associar uma organela a qualquer função só pelo nome.",
                new String[]{"b_celula"},
                q("Qual estrutura está diretamente ligada à síntese de proteínas?",0,
                        "ribossomo","Correto.",null,
                        "lisossomo","Ligado à digestão intracelular.",null,
                        "centríolo apenas","Participa de processos celulares, mas não síntese de proteínas.",null,
                        "parede celular","Estrutura de suporte/proteção, não síntese proteica.",null),
                q("Uma célula especializada em secreção intensa de proteínas tende a ter desenvolvido especialmente:",2,
                        "apenas parede celular","Células animais secretoras nem possuem parede.",null,
                        "apenas cloroplastos","Cloroplastos ligam-se à fotossíntese.",null,
                        "retículo endoplasmático rugoso e complexo de Golgi","Correto.",null,
                        "nenhuma organela","Especialização envolve organização celular específica.",null)));

        add(m, n("b_cadeia","Biologia","Cadeia alimentar, níveis tróficos e energia",2,
                "Cadeia alimentar representa transferência de matéria e energia por alimentação. Produtores formam matéria orgânica; consumidores obtêm energia alimentando-se; decompositores reciclam matéria.",
                "ENERGIA flui e diminui ao longo dos níveis.\nMATÉRIA circula nos ecossistemas.",
                "produtor = autotrófico\nconsumidor primário = alimenta-se de produtor\ndecompositor = atua sobre matéria orgânica morta\nnível trófico = posição na transferência alimentar",
                "capim → gafanhoto → sapo → cobra. Capim é produtor; gafanhoto consumidor primário; sapo secundário.",
                "A energia disponível tende a diminuir nos níveis superiores porque parte é dissipada em processos metabólicos, principalmente como calor.",
                "Contraexemplo: decompositores aparecem apenas no fim da cadeia. Eles atuam sobre restos de organismos de vários níveis.",
                "Erro comum: seta indicar 'quem come quem' no sentido contrário; em diagramas de fluxo energético, aponta para quem recebe energia.",
                new String[]{"b_ecologia"},
                q("Na cadeia planta → coelho → raposa, o coelho é:",1,
                        "produtor","Planta é produtor.",null,
                        "consumidor primário","Correto.",null,
                        "decompositor","Não.",null,
                        "consumidor terciário","Ocupa nível anterior.",null),
                q("Por que normalmente há menos energia disponível em níveis tróficos mais altos?",3,
                        "Porque energia é criada apenas nos predadores","Energia não é criada assim.",null,
                        "Porque matéria desaparece totalmente","Matéria é reciclada.",null,
                        "Porque produtores não possuem energia","Produtores capturam/transformam energia.",null,
                        "Porque organismos usam energia no metabolismo e parte é dissipada como calor em cada transferência","Correto.",null)));

        add(m, n("b_evolucao","Biologia","Seleção natural e evolução",3,
                "Evolução é mudança em populações ao longo das gerações. Seleção natural ocorre quando variações hereditárias afetam sobrevivência/reprodução em determinado ambiente.",
                "INDIVÍDUO não evolui por necessidade; POPULAÇÕES mudam ao longo das gerações.",
                "variação = diferenças entre indivíduos\nhereditário = transmissível geneticamente\naptidão = sucesso reprodutivo relativo no contexto\nseleção = diferenças de reprodução associadas às variações",
                "Bactérias resistentes não aparecem porque 'decidiram' resistir ao antibiótico. Variações existentes/surgidas permitem que algumas sobrevivam e deixem mais descendentes; a frequência da resistência aumenta.",
                "Uma característica vantajosa num ambiente pode ser neutra ou desvantajosa em outro.",
                "Contraexemplo: girafas alongaram pescoço por esforço e transmitiram esse alongamento adquirido diretamente.",
                "Erro comum: usar linguagem de intenção ('a espécie quis', 'precisou e criou').",
                new String[]{"b_dna","b_ecologia"},
                q("Qual frase expressa melhor seleção natural?",2,
                        "Indivíduos mudam genes porque precisam sobreviver","Necessidade não direciona mutações dessa forma.",null,
                        "Todos os indivíduos de uma população são geneticamente idênticos","Há variação.",null,
                        "Variações hereditárias que favorecem reprodução podem aumentar de frequência ao longo das gerações","Correto.",null,
                        "A evolução sempre busca perfeição","Não há objetivo final obrigatório.",null),
                q("Uso frequente de antibiótico pode favorecer aumento de bactérias resistentes porque:",0,
                        "bactérias resistentes sobrevivem mais e deixam descendentes quando as sensíveis são eliminadas","Correto.",null,
                        "o antibiótico ensina cada bactéria a criar resistência intencionalmente","Não é mecanismo evolutivo.",null,
                        "todas as bactérias se tornam resistentes ao mesmo tempo","Não.",null,
                        "resistência não pode ser herdada","Pode envolver características genéticas transmissíveis.","b_dna")));

        add(m, n("b_sistemas","Biologia","Sistemas digestório, respiratório e circulatório",3,
                "Sistemas corporais trabalham integrados. Digestório fornece nutrientes; respiratório realiza trocas gasosas; circulatório transporta substâncias pelo corpo.",
                "DIGESTÓRIO transforma/absorve.\nRESPIRATÓRIO troca gases.\nCIRCULATÓRIO transporta.",
                "alvéolos = estruturas pulmonares de troca gasosa\nintestino delgado = principal absorção de muitos nutrientes\nsangue = transporta gases, nutrientes, resíduos e sinais",
                "Oxigênio entra nos pulmões, difunde-se nos alvéolos para o sangue e é transportado aos tecidos. Nutrientes absorvidos no intestino também entram em circuitos de transporte.",
                "Integração explica por que exercício aumenta frequência respiratória e cardíaca: tecidos demandam maior entrega de O₂ e remoção de CO₂.",
                "Contraexemplo: sistemas funcionam isolados e independentes.",
                "Erro comum: dizer que digestão acontece apenas no estômago.",
                new String[]{"b_celula"},
                q("Onde ocorre troca gasosa principal entre ar e sangue nos pulmões?",1,
                        "estômago","Sistema digestório.",null,
                        "alvéolos","Correto.",null,
                        "ossos longos","Não são superfície respiratória.",null,
                        "rins","Sistema excretor.",null),
                q("Durante exercício, aumento simultâneo da ventilação e dos batimentos ajuda principalmente a:",2,
                        "parar todo metabolismo","Metabolismo aumenta.",null,
                        "impedir transporte de oxigênio","Faz o oposto.",null,
                        "aumentar entrada de O₂ e seu transporte aos tecidos, além da remoção de CO₂","Correto.",null,
                        "substituir completamente a digestão","Não.",null)));

        // ================= HISTÓRIA =================
        add(m, n("h_renascimento_reforma","História","Renascimento, Humanismo e Reforma",2,
                "Renascimento valorizou referências clássicas, humanismo e novas práticas artísticas/científicas em contextos urbanos europeus. Reforma Protestante rompeu a unidade religiosa católica ocidental e teve causas religiosas, políticas, sociais e econômicas.",
                "RENASCIMENTO = mudanças culturais.\nREFORMA = ruptura religiosa com efeitos políticos e sociais.",
                "humanismo = valorização do estudo do humano e textos clássicos\nindulgências = prática criticada por reformadores\nimprensa = ampliou circulação de textos\nContrarreforma = resposta/reorganização católica",
                "Lutero criticou práticas da Igreja e defendeu princípios teológicos próprios; sua atuação encontrou apoio em conflitos políticos existentes no Sacro Império.",
                "A imprensa não 'causou sozinha' a Reforma, mas facilitou circulação de ideias e debates.",
                "Contraexemplo: Renascimento abandonou toda religião. Muitos artistas/pensadores eram profundamente religiosos.",
                "Erro comum: buscar uma causa única para processos complexos.",
                new String[]{"h_tempo_fonte"},
                q("Qual fator ajudou a ampliar a circulação de ideias reformistas no século XVI?",1,
                        "desaparecimento da escrita","O período teve expansão de impressos.",null,
                        "difusão da imprensa","Correto.",null,
                        "fim das disputas políticas","Disputas eram relevantes.",null,
                        "proibição de qualquer tradução bíblica em toda Europa sem exceções","Não explica a circulação reformista.",null),
                q("Por que é inadequado explicar a Reforma apenas como disputa teológica?",3,
                        "Porque não houve questões religiosas","Houve e foram centrais.",null,
                        "Porque ocorreu antes do cristianismo","Não.",null,
                        "Porque não produziu efeitos políticos","Produziu.",null,
                        "Porque interesses políticos, sociais e econômicos também interagiram com as controvérsias religiosas","Correto.",null)));

        add(m, n("h_absolutismo","História","Absolutismo e formação dos Estados modernos",2,
                "Absolutismo refere-se a processos de concentração de autoridade monárquica em certos Estados europeus modernos, sem significar poder literalmente ilimitado em qualquer situação.",
                "ABSOLUTISMO = concentração de autoridade, não ausência total de limites reais.",
                "centralização = fortalecimento de instituições do poder central\nburocracia = administração estatal\nexército permanente = força ligada ao Estado\nsoberania = autoridade política sobre território",
                "Monarquias ampliaram tributação, burocracia e forças militares, reduzindo autonomias de poderes locais em vários contextos.",
                "Mesmo reis fortes precisavam negociar com elites, leis, tradições, recursos e instituições.",
                "Contraexemplo: absolutismo significa que o rei podia fazer literalmente qualquer coisa sem resistência.",
                "Erro comum: confundir centralização com Estado moderno democrático.",
                new String[]{"h_tempo_fonte","h_mercantilismo"},
                q("Qual processo se associa à formação de monarquias centralizadas?",0,
                        "ampliação de burocracias e mecanismos fiscais do poder central","Correto.",null,
                        "desaparecimento de qualquer imposto","Contraria a expansão estatal.",null,
                        "fim de exércitos ligados ao Estado","Ocorreu fortalecimento de forças permanentes.",null,
                        "fragmentação crescente obrigatória do território","Centralização aponta tendência oposta.",null),
                q("Por que historiadores evitam interpretar 'absoluto' como poder sem qualquer limite prático?",2,
                        "Porque reis não existiam","Existiam monarquias.",null,
                        "Porque não havia conflitos sociais","Havia.",null,
                        "Porque governantes dependiam de recursos, instituições, elites e enfrentavam resistências","Correto.",null,
                        "Porque todos os Estados eram democracias modernas","Não.",null)));

        add(m, n("h_expansao","História","Expansão marítima europeia",2,
                "Expansão marítima dos séculos XV-XVI articulou comércio, tecnologias de navegação, poder monárquico, interesses religiosos e busca de rotas/riquezas.",
                "NAVEGAÇÕES = comércio + Estado + técnica + religião + disputa.",
                "caravela = embarcação associada à expansão portuguesa\nrota atlântica = redes pelo oceano\ncolonização = domínio e ocupação de territórios\nmercantilismo = práticas econômicas associadas aos Estados modernos",
                "Portugal combinou posição atlântica, experiência marítima, centralização política relativa e interesses comerciais para avançar na costa africana e chegar ao oceano Índico.",
                "A expansão produziu intercâmbios, violência, escravização, conquistas e novas redes globais.",
                "Contraexemplo: as navegações ocorreram apenas por curiosidade científica.",
                "Erro comum: transformar múltiplas causas em uma única 'busca de especiarias'.",
                new String[]{"h_mercantilismo","h_absolutismo"},
                q("Qual conjunto explica melhor a expansão marítima portuguesa?",2,
                        "apenas desejo individual de aventureiros","Insuficiente.",null,
                        "ausência de comércio internacional","Havia intenso comércio e disputa por rotas.",null,
                        "interesses comerciais, experiência náutica, apoio estatal e contexto religioso/político","Correto.",null,
                        "fim de tecnologias de navegação","O desenvolvimento de técnicas ajudou a expansão.",null),
                q("Uma consequência ampla das navegações europeias foi:",1,
                        "isolamento crescente entre continentes","Ocorreu maior conexão forçada/voluntária entre regiões.",null,
                        "formação de redes atlânticas de comércio, conquista, colonização e escravização","Correto.",null,
                        "fim imediato da escravidão","O tráfico atlântico de escravizados expandiu-se.",null,
                        "desaparecimento de conflitos imperiais","Conflitos aumentaram em vários espaços.",null)));

        add(m, n("h_colonia","História","Colonização portuguesa e economia açucareira",2,
                "Colonização portuguesa na América envolveu ocupação territorial, exploração econômica, instituições administrativas e uso de trabalho coercitivo, inclusive escravidão indígena e africana em diferentes contextos.",
                "COLÔNIA = território integrado a relações de poder e exploração metropolitana.",
                "capitanias hereditárias = divisão administrativa inicial\ngoverno-geral = tentativa de centralização administrativa\nengenho = unidade produtiva ligada ao açúcar\nplantation = grande propriedade, monocultura, trabalho compulsório e produção para mercado externo em modelo clássico",
                "A economia açucareira articulava propriedade de terra, produção no engenho, comércio atlântico e escravização.",
                "A colônia não era economicamente uniforme: havia pecuária, agricultura de abastecimento, atividades urbanas e outras regiões produtivas.",
                "Contraexemplo: toda a população colonial trabalhava em engenhos de açúcar.",
                "Erro comum: tratar a colonização como ocupação pacífica de espaço vazio, ignorando povos indígenas.",
                new String[]{"h_expansao","h_mercantilismo"},
                q("Qual característica se associa ao modelo açucareiro colonial em áreas do Brasil?",1,
                        "produção apenas para autoconsumo familiar","A produção tinha forte orientação ao mercado externo.",null,
                        "grandes unidades, produção açucareira e trabalho escravizado em ampla escala","Correto.",null,
                        "ausência de comércio atlântico","O comércio atlântico era essencial.",null,
                        "fim da concentração fundiária","Houve grande propriedade em muitas áreas.",null),
                q("Por que o Governo-Geral foi criado após a experiência inicial das capitanias?",3,
                        "Para eliminar qualquer autoridade portuguesa","Objetivo era reforçar coordenação colonial.",null,
                        "Para declarar independência","Não.",null,
                        "Para abolir a exploração colonial","Não.",null,
                        "Para ampliar coordenação e centralização administrativa diante de dificuldades do sistema inicial","Correto.",null)));

        add(m, n("h_escravidao","História","Escravidão africana, indígena e tráfico atlântico",3,
                "Escravidão colonial foi sistema de coerção, violência e exploração. Povos indígenas e africanos resistiram de diversas formas; o tráfico atlântico integrou redes econômicas e políticas de grande escala.",
                "ESCRAVIDÃO = sistema imposto por violência; resistência esteve presente.",
                "tráfico atlântico = deslocamento forçado de africanos escravizados\nquilombo = comunidade de resistência com formas variadas\nalforria = libertação jurídica em certas condições\ndiáspora africana = dispersão forçada e formação de comunidades/culturas",
                "O trabalho escravizado esteve em agricultura, mineração, cidades, serviços e atividades domésticas. Pessoas escravizadas preservaram e recriaram culturas e construíram estratégias de resistência.",
                "Resistência não se resume a fugas: negociação, formação de redes, revoltas, manutenção cultural e ações jurídicas também ocorreram.",
                "Contraexemplo: pessoas escravizadas foram passivas e sem agência histórica.",
                "Erro comum: descrever escravidão apenas como 'mão de obra' sem reconhecer violência e condição humana dos sujeitos.",
                new String[]{"h_colonia","h_tempo_fonte"},
                q("Qual afirmação histórica é mais adequada?",2,
                        "A escravidão colonial envolveu apenas trabalho rural","Também houve trabalho urbano, mineração e outros.",null,
                        "Pessoas escravizadas não resistiram","Houve diversas formas de resistência.",null,
                        "O tráfico atlântico foi um sistema de deslocamento forçado e comércio de pessoas ligado à economia colonial","Correto.",null,
                        "Quilombos eram instituições criadas pelas metrópoles para ampliar a escravidão","Quilombos relacionam-se a resistência/autonomia de populações negras em contextos diversos.",null),
                q("Por que estudar resistência é importante para compreender a escravidão?",0,
                        "Porque evidencia que pessoas escravizadas agiam, negociavam, fugiam, preservavam culturas e contestavam o sistema","Correto.",null,
                        "Porque prova que a escravidão não foi violenta","O oposto: resistência ocorreu dentro de sistema violento.",null,
                        "Porque elimina a importância da economia","Não elimina; amplia a análise social e política.",null,
                        "Porque todos resistiram exatamente da mesma forma","As estratégias foram diversas.",null)));

        add(m, n("h_iluminismo_francesa","História","Iluminismo e Revolução Francesa",3,
                "Iluminismo reuniu correntes que criticaram autoridades tradicionais e discutiram razão, direitos, liberdade e organização política. A Revolução Francesa resultou de crise fiscal, conflitos sociais e políticos e ideias diversas, passando por fases distintas.",
                "ILUMINISMO = crítica e novas ideias políticas.\nREVOLUÇÃO FRANCESA = processo, não um único dia.",
                "Antigo Regime = ordem política/social anterior\nprivilégios = direitos diferenciados por estamento\ncidadania = participação e direitos políticos em transformação\nDeclaração dos Direitos = marco de linguagem universalista, embora aplicação fosse limitada",
                "A crise fiscal da monarquia e os conflitos sobre tributação ajudaram a desencadear a convocação dos Estados Gerais em 1789.",
                "A revolução passou por monarquia constitucional, república, radicalização, reação e Diretório; seus princípios não foram aplicados de modo linear ou igualitário.",
                "Contraexemplo: todos os iluministas defendiam exatamente as mesmas ideias.",
                "Erro comum: resumir Revolução Francesa a 'povo contra rei' sem classes, instituições, guerra e fases.",
                new String[]{"h_absolutismo","h_tempo_fonte"},
                q("Qual crítica iluminista aparece em debates do século XVIII?",1,
                        "defesa obrigatória de privilégios de nascimento","Muitos autores criticaram privilégios.",null,
                        "questionamento de poderes absolutos e discussão de direitos/limites ao governo","Correto.",null,
                        "rejeição de qualquer uso da razão","Contradiz eixo importante do movimento.",null,
                        "retorno universal ao feudalismo","Não.",null),
                q("Por que 1789 não deve ser tratado como explicação completa da Revolução Francesa?",3,
                        "Porque nada aconteceu em 1789","Aconteceram eventos decisivos.",null,
                        "Porque a França não existia","Existia.",null,
                        "Porque a revolução acabou no mesmo dia","O processo se estendeu por anos.",null,
                        "Porque a revolução teve causas anteriores e fases posteriores com mudanças políticas e sociais distintas","Correto.",null)));

        // ================= GEOGRAFIA =================
        add(m, n("g_relevo","Geografia","Tectonismo, relevo e agentes externos",2,
                "Relevo resulta de processos internos, como tectonismo/vulcanismo, e externos, como intemperismo, erosão, transporte e sedimentação.",
                "INTERNO constrói/deforma.\nEXTERNO desgasta, transporta e deposita.",
                "placas tectônicas = blocos da litosfera\nintemperismo = desagregação/decomposição de rochas\nerosão = remoção/transporte\nsedimentação = deposição",
                "Montanhas podem relacionar-se a convergência de placas; rios depois erodem e remodelam essas formas ao longo do tempo.",
                "Terremotos se concentram frequentemente em limites de placas, mas também podem ocorrer em regiões intraplaca.",
                "Contraexemplo: erosão e intemperismo são exatamente a mesma coisa.",
                "Erro comum: imaginar relevo como forma fixa e imutável.",
                new String[]{"g_mapa_escala"},
                q("Qual processo é agente externo de modelagem do relevo?",2,
                        "movimento de placas","Processo interno tectônico.",null,
                        "vulcanismo","Interno.",null,
                        "erosão fluvial","Correto.",null,
                        "formação do magma","Processo interno.",null),
                q("Por que grandes cadeias montanhosas podem ocorrer em limites convergentes de placas?",0,
                        "Porque compressão e colisão deformam/soerguem a crosta em certos contextos","Correto.",null,
                        "Porque rios deixam de existir","Não.",null,
                        "Porque todo limite convergente é plano","Oposto.",null,
                        "Porque intemperismo cria placas tectônicas","Relação invertida.",null)));

        add(m, n("g_hidrografia","Geografia","Hidrografia e bacias",2,
                "Bacia hidrográfica é área drenada por um rio principal e seus afluentes. Divisores de água separam bacias.",
                "BACIA = área que envia água para a mesma rede de drenagem.",
                "nascente = origem do curso\nafluente = rio que deságua em outro\nfoz = onde o rio termina\ndivisor de águas = relevo que separa drenagens",
                "Uso do solo a montante pode afetar água a jusante: desmatamento, impermeabilização e poluição alteram escoamento e qualidade.",
                "Gestão de rios exige pensar em toda a bacia, pois limites naturais não coincidem necessariamente com limites municipais.",
                "Contraexemplo: bacia hidrográfica é apenas o leito do rio.",
                "Erro comum: tratar rio como sistema isolado do relevo e ocupação humana.",
                new String[]{"g_relevo","g_mapa_escala"},
                q("Um afluente é:",1,
                        "a área entre duas bacias","Isso é relacionado ao divisor.",null,
                        "um curso d'água que deságua em outro rio","Correto.",null,
                        "a foz oceânica obrigatoriamente","Não.",null,
                        "uma montanha sem drenagem","Não.",null),
                q("Por que impermeabilização urbana pode aumentar picos de cheia?",2,
                        "Porque aumenta infiltração no solo","Impermeabilização reduz infiltração.",null,
                        "Porque elimina chuva","Não.",null,
                        "Porque aumenta escoamento superficial rápido para a rede de drenagem","Correto.",null,
                        "Porque transforma rios em montanhas","Não.",null)));

        add(m, n("g_biomas","Geografia","Biomas brasileiros e vegetação",2,
                "Bioma reúne grandes conjuntos de ecossistemas associados a clima, vegetação, fauna, solos e processos históricos. No Brasil destacam-se Amazônia, Cerrado, Caatinga, Mata Atlântica, Pantanal e Pampa.",
                "BIOMA não é só 'tipo de árvore': clima, solo, água, fauna e uso humano interagem.",
                "Amazônia = floresta tropical extensa\nCerrado = savânico com forte sazonalidade\nCaatinga = semiárido e adaptações à seca\nPantanal = planície com pulso de inundação",
                "Cerrado possui árvores de troncos retorcidos e raízes profundas em muitas formações, adaptadas a sazonalidade hídrica e fogo em contexto ecológico.",
                "Desmatamento altera biodiversidade, ciclos de água e carbono e pode fragmentar habitats.",
                "Contraexemplo: Caatinga é 'deserto sem vida'. Possui alta diversidade e espécies adaptadas ao semiárido.",
                "Erro comum: associar cada bioma a uma única paisagem uniforme.",
                new String[]{"g_clima","b_ecologia"},
                q("Qual bioma brasileiro se associa fortemente a planície com ciclos de inundação?",3,
                        "Pampa","Campos do sul.",null,
                        "Caatinga","Semiárido.",null,
                        "Cerrado","Savana tropical, não principal planície alagável.",null,
                        "Pantanal","Correto.",null),
                q("Por que desmatamento amazônico pode influenciar além do local removido?",1,
                        "Porque floresta não participa do ciclo da água","Participa intensamente.",null,
                        "Porque altera evapotranspiração, fluxos de umidade, carbono e conectividade ecológica","Correto.",null,
                        "Porque elimina a rotação da Terra","Não.",null,
                        "Porque transforma imediatamente todo o Brasil em deserto","Afirmação exagerada e não sustentada.",null)));

        add(m, n("g_urbanizacao","Geografia","Urbanização, metropolização e rede urbana",3,
                "Urbanização é aumento da participação/população urbana e transformação do espaço. Metropolização envolve concentração e integração funcional em grandes aglomerações. Rede urbana conecta cidades por fluxos.",
                "URBANIZAÇÃO = crescimento/transformação urbana.\nREDE URBANA = cidades conectadas por fluxos.",
                "metrópole = cidade com forte influência regional/nacional\nconurbação = continuidade física entre áreas urbanas\nsegregação socioespacial = separação desigual de grupos no espaço",
                "Uma pessoa mora em município periférico e trabalha diariamente no núcleo metropolitano: deslocamento pendular evidencia integração funcional da metrópole.",
                "Urbanização pode ocorrer com infraestrutura insuficiente, produzindo desigualdade de acesso a transporte, saneamento e moradia.",
                "Contraexemplo: urbanização significa apenas construir prédios altos.",
                "Erro comum: confundir crescimento urbano com melhoria automática da qualidade de vida.",
                new String[]{"g_populacao"},
                q("Deslocamento diário entre município residencial e núcleo de empregos de uma metrópole é exemplo de:",1,
                        "êxodo internacional","Não envolve mudança internacional de residência.",null,
                        "movimento pendular","Correto.",null,
                        "intemperismo","Processo geomorfológico.","g_relevo",
                        "latitude","Coordenada geográfica.","g_coordenadas"),
                q("Uma consequência possível de urbanização rápida sem planejamento adequado é:",2,
                        "distribuição automática e igual de serviços","Não é automática.",null,
                        "fim dos deslocamentos urbanos","Podem crescer.",null,
                        "expansão periférica com déficits de transporte/saneamento e segregação","Correto.",null,
                        "desaparecimento da rede urbana","Ocorre maior integração entre cidades em muitos casos.",null)));

        add(m, n("g_industrial","Geografia","Industrialização e setores da economia",3,
                "Industrialização transforma organização produtiva, território, trabalho e redes logísticas. Setores primário, secundário e terciário classificam atividades de forma geral.",
                "PRIMÁRIO extrai/produz recursos.\nSECUNDÁRIO transforma.\nTERCIÁRIO presta serviços/comercializa.",
                "indústria = transformação de matérias-primas/insumos\ndesconcentração industrial = deslocamento de atividades para novas áreas\nlogística = organização de fluxos de bens",
                "Uma fábrica de automóveis é setor secundário; mineração é primário; transporte e comércio são terciários, embora cadeias modernas integrem todos.",
                "Indústrias escolhem localização considerando mercado, infraestrutura, energia, trabalho, incentivos e logística.",
                "Contraexemplo: toda atividade moderna pertence ao setor secundário.",
                "Erro comum: tratar setores como isolados e não como cadeia interdependente.",
                new String[]{"g_urbanizacao","g_globalizacao"},
                q("Qual atividade pertence principalmente ao setor secundário?",2,
                        "cultivo de soja","Primário.",null,
                        "serviço bancário","Terciário.",null,
                        "fabricação de máquinas","Correto.",null,
                        "extração de minério","Primário.",null),
                q("Por que uma indústria pode sair de um centro tradicional para outra região?",3,
                        "porque localização nunca importa","Importa.",null,
                        "porque transporte deixou de existir","Logística continua central.",null,
                        "porque indústrias não usam infraestrutura","Usam.",null,
                        "por combinação de custos, infraestrutura, incentivos, mercado e logística","Correto.",null)));

        add(m, n("g_agrario","Geografia","Espaço agrário e estrutura fundiária",3,
                "Espaço agrário envolve produção agropecuária, propriedade da terra, tecnologia, trabalho, mercados e conflitos territoriais.",
                "ESTRUTURA FUNDIÁRIA = como a terra está distribuída e organizada.",
                "latifúndio/minifúndio = categorias ligadas a tamanho/uso em contextos específicos\nagricultura familiar = produção baseada principalmente em trabalho familiar segundo critérios legais próprios\nagronegócio = redes empresariais ligadas à produção e circulação agropecuária",
                "Mecanização pode elevar produtividade e reduzir certas demandas de trabalho, mas efeitos sociais dependem da cultura, região e estrutura produtiva.",
                "Concentração fundiária significa grande parcela da terra controlada por número relativamente pequeno de proprietários.",
                "Contraexemplo: agricultura familiar é sinônimo de ausência de tecnologia.",
                "Erro comum: reduzir o campo a produção de alimentos e ignorar exportação, energia, fibras, mineração e conflitos.",
                new String[]{"g_populacao","g_globalizacao"},
                q("Estrutura fundiária refere-se principalmente a:",0,
                        "distribuição e organização da propriedade/posse da terra","Correto.",null,
                        "altura média das montanhas","Geomorfologia.","g_relevo",
                        "posição de latitude das fazendas","Coordenadas não definem estrutura fundiária.","g_coordenadas",
                        "apenas quantidade de chuva","Clima influencia agricultura, mas não define o conceito.","g_clima"),
                q("Por que mecanização agrícola não produz o mesmo efeito social em qualquer lugar?",2,
                        "porque máquinas não existem no campo","Existem.",null,
                        "porque produtividade nunca muda","Pode mudar.",null,
                        "porque efeitos dependem do tipo de cultivo, acesso à tecnologia, relações de trabalho e estrutura da propriedade","Correto.",null,
                        "porque agricultura não usa mão de obra","Usa em diferentes intensidades.",null)));

        add(m, n("g_geopolitica","Geografia","Geopolítica, território e blocos econômicos",3,
                "Geopolítica analisa relações de poder ligadas a territórios, recursos, fronteiras, redes e estratégias dos Estados e outros atores. Blocos econômicos criam diferentes níveis de integração entre países.",
                "TERRITÓRIO = espaço apropriado por relações de poder.",
                "fronteira = limite/área de contato político\nsoberania = autoridade estatal sobre território\nbloco econômico = acordo de integração com diferentes graus\ngeopolítica = poder + território + estratégia",
                "Uma disputa por rota marítima pode envolver comércio, segurança, recursos e projeção de poder ao mesmo tempo.",
                "Blocos econômicos não eliminam automaticamente soberania dos membros; regras dependem do tipo de integração.",
                "Contraexemplo: geopolítica é apenas decorar capitais e bandeiras.",
                "Erro comum: explicar conflito por uma única causa geográfica e ignorar história/política/economia.",
                new String[]{"g_globalizacao","h_tempo_fonte"},
                q("Qual situação é claramente geopolítica?",1,
                        "cálculo da área de um círculo","Matemática.","m_circulo",
                        "disputa entre Estados por controle de rota estratégica e recursos","Correto.",null,
                        "classificação de substantivos","Português.","p_substantivo",
                        "divisão celular","Biologia.","b_celula"),
                q("Por que blocos econômicos possuem impactos diferentes?",3,
                        "porque todos têm regras idênticas","Não.",null,
                        "porque nenhum envolve comércio","Comércio é central em muitos.",null,
                        "porque fronteiras deixam de existir fisicamente","Não necessariamente.",null,
                        "porque variam em grau de integração, regras comerciais, mobilidade e instituições comuns","Correto.",null)));

        return m;
    }

    private static void add(Map<String, StudyCatalog.Node> m, StudyCatalog.Node n) { m.put(n.id,n); }
    private static StudyCatalog.Node n(String id,String subject,String title,int level,String summary,String memory,String terms,String detail,String worked,String counter,String trap,String[] prereq,StudyCatalog.Question check,StudyCatalog.Question transfer) {
        return new StudyCatalog.Node(id,subject,title,level,summary,memory,terms,detail,worked,counter,trap,prereq,check,transfer);
    }
    private static StudyCatalog.Question q(String prompt,int correct,
                                            String o0,String f0,String r0,
                                            String o1,String f1,String r1,
                                            String o2,String f2,String r2,
                                            String o3,String f3,String r3) {
        return new StudyCatalog.Question(prompt,correct,new String[]{o0,o1,o2,o3},new String[]{f0,f1,f2,f3},new String[]{r0,r1,r2,r3});
    }
}
